/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Community;

import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSplitPane;
import ComEnterprise.City;
import ComEnterprise.CityCatalouge;
import ComEnterprise.Community;
import ComEnterprise.House;
import ComEnterprise.LoginInfo;
import ComEnterprise.People;
import ComEnterprise.PeopleCatalouge;
import UserInterface.Admin.SystemAdmin;

/**
 *
 * @author namithajc
 */
public class CommunityDetails extends javax.swing.JPanel {

    /**
     * Creates new form AddCommunity
     */
    CityCatalouge cityLog;
    String selectedComm;
    JSplitPane jSplitPane2;
    City selectedCity;
    JPanel jPanel2;
    boolean isView;
    public CommunityDetails(CityCatalouge cityLog, String selectedComm, JSplitPane jSplitPane2, City selectedCity, JPanel jPanel2, boolean isView) {
        initComponents();
        this.jSplitPane2 = jSplitPane2;
        this.cityLog = cityLog;
        this.selectedComm = selectedComm;
        this.selectedCity = selectedCity;
        this.jPanel2 = jPanel2; 
        this.isView = isView;
        jEditBtn.setEnabled(false);
        jCityName.setText(selectedComm);
        if(!isView){
            jEditBtn.setEnabled(false);
        }
        if(isView){
            disableFields(false);
            jButton1.setEnabled(false);
            jEditBtn.setEnabled(true);
            Community selComm = selectedCity.getCommunityCatalog().searchCommunity(selectedComm);
            jCityName.setText(selComm.getCommunityName());
            for(int i =0 ;i< selectedCity.getCommunityCatalog().size();i++){
                PeopleCatalouge peopLog = selectedCity.getCommunityCatalog().get(i).getPeopleCatalog();
                for(int j = 0; j< peopLog.size();j++){
                    People p = peopLog.get(j);
                    if(p.isCommunityAdmin()){
                        jId.setText(p.getId());
                        jName.setText(p.getName());
                        jPhone.setText(p.getPhone());
                        jEmail.setText(p.getEmail());
                        jDateChooser1.setDate(p.getDob());
                        jStreetNumber.setText(p.getHouse().getStreetName());
                        jZipCode.setText(p.getHouse().getZipCode());
                        jAptNumber.setText(p.getHouse().getApartementNo());
                        break;
                    }
                }
            }

        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPhone = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jAptNumber = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jId = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jStreetNumber = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jZipCode = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jEditBtn = new javax.swing.JButton();
        jGender = new javax.swing.JComboBox<>();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jCityName = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setBackground(new java.awt.Color(170, 185, 207));
        setPreferredSize(new java.awt.Dimension(800, 500));

        jLabel2.setFont(new java.awt.Font("Lava Kannada", 1, 14)); // NOI18N

        jLabel3.setBackground(new java.awt.Color(247, 247, 255));
        jLabel3.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLabel3.setText("Name:");

        jName.setBackground(new java.awt.Color(247, 247, 255));
        jName.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jNameKeyPressed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(247, 247, 255));
        jLabel4.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLabel4.setText("Gender:");

        jLabel5.setBackground(new java.awt.Color(247, 247, 255));
        jLabel5.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLabel5.setText("Dob:");

        jLabel6.setBackground(new java.awt.Color(247, 247, 255));
        jLabel6.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLabel6.setText("Email:");

        jEmail.setBackground(new java.awt.Color(247, 247, 255));
        jEmail.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jEmailKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jEmailKeyReleased(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(247, 247, 255));
        jLabel7.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLabel7.setText("Phone:");

        jPhone.setBackground(new java.awt.Color(247, 247, 255));
        jPhone.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPhoneKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPhoneKeyReleased(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(247, 247, 255));
        jLabel8.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLabel8.setText("Apt No:");

        jAptNumber.setBackground(new java.awt.Color(247, 247, 255));
        jAptNumber.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N

        jLabel9.setBackground(new java.awt.Color(247, 247, 255));
        jLabel9.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLabel9.setText("ID:");

        jId.setBackground(new java.awt.Color(247, 247, 255));
        jId.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N

        jLabel10.setBackground(new java.awt.Color(247, 247, 255));
        jLabel10.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLabel10.setText("St Name:");

        jStreetNumber.setBackground(new java.awt.Color(247, 247, 255));
        jStreetNumber.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N

        jLabel11.setBackground(new java.awt.Color(247, 247, 255));
        jLabel11.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLabel11.setText("ZipCode:");

        jZipCode.setBackground(new java.awt.Color(247, 247, 255));
        jZipCode.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N

        jButton1.setBackground(new java.awt.Color(247, 247, 255));
        jButton1.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jEditBtn.setBackground(new java.awt.Color(247, 247, 255));
        jEditBtn.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jEditBtn.setText("Edit");
        jEditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEditBtnActionPerformed(evt);
            }
        });

        jGender.setBackground(new java.awt.Color(247, 247, 255));
        jGender.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        jDateChooser1.setBackground(new java.awt.Color(247, 247, 255));

        jLabel1.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLabel1.setText("Community Name :");

        jCityName.setBackground(new java.awt.Color(247, 247, 255));
        jCityName.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Lava Kannada", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 51, 51));

        jLabel13.setFont(new java.awt.Font("Lava Kannada", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(371, 371, 371)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(142, 142, 142)
                .addComponent(jEditBtn)
                .addGap(275, 275, 275))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCityName, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel9)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jId, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jName, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jGender, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jAptNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(198, 198, 198)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jPhone)
                    .addComponent(jEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jStreetNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(114, 114, 114))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCityName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel9)
                    .addComponent(jId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(jName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel10)
                    .addComponent(jLabel5)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jStreetNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jAptNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jEditBtn))
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        boolean isPresent = false;
        PeopleCatalouge pepLog = selectedCity.getCommunityCatalog().searchCommunity(selectedComm).getPeopleCatalog();
        String name = jName.getText();
        String id = jId.getText();
        Date dob = jDateChooser1.getDate();
        String gender = (String) jGender.getSelectedItem();
        String phoneNo = jPhone.getText();
        String email = jEmail.getText();
        String aptNo = jAptNumber.getText();
        String streetNo = jStreetNumber.getText();
        String zipCode = jZipCode.getText();
        String temp[] = jDateChooser1.getDate().toString().split(" ");
        int length = temp.length;
        String dobYear = temp[length-1];
        String communityName = jCityName.getText();
        
        
        if(name.trim().length() == 0 ||id.trim().length() == 0|| gender.trim().length() == 0 || phoneNo.trim().length() == 0|| email.trim().length() == 0 || aptNo.trim().length() == 0 || streetNo.trim().length() == 0|| zipCode.trim().length() ==0 ){
            JOptionPane.showMessageDialog(this, "All Fields must be entered");
        }
        else{
        for(int i = 0;i < pepLog.size();i++){
            String peopId = pepLog.get(i).getId();
            if(peopId.equalsIgnoreCase(id)){
                isPresent = true;
                System.out.println("Reached");
                People present = pepLog.get(i);
                present.setDob(dob);
                present.setName(name);
                present.setGender(gender);
                present.setPhone(phoneNo);
                present.setId(id);
                present.setEmail(email);
                present.setCommunityAdmin(true);
                present.setHouse(new House(aptNo,streetNo,zipCode));
                present.setLoginInfo(new LoginInfo(name.replaceAll("\\s", "")+id,name.substring(0,3)+dobYear)); 
                SystemAdmin sysadmin = new SystemAdmin(jSplitPane2,cityLog,jPanel2,true);
                jSplitPane2.setRightComponent(sysadmin);
            }
        }
        if(!isPresent){
            System.out.println("Reached");
            People p = new People();
            p.setDob(dob);
            p.setName(name);
            p.setGender(gender);
            p.setPhone(phoneNo);
            p.setId(id);
            p.setEmail(email);
            p.setCommunityAdmin(true);
            p.setHouse(new House(aptNo,streetNo,zipCode));
            p.setLoginInfo(new LoginInfo(name.replaceAll("\\s", "")+id,name.substring(0,3)+dobYear));
            Community c = new Community();
            PeopleCatalouge peopLog = new PeopleCatalouge();
            peopLog.addPeople(p);
            c.setCommunityName(communityName);
            c.setPeopleCatalog(peopLog);
            selectedCity.getCommunityCatalog().addCommunity(c);
            SystemAdmin sysadmin = new SystemAdmin(jSplitPane2,cityLog,jPanel2,true);
            jSplitPane2.setRightComponent(sysadmin);
        }     
        }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jEditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEditBtnActionPerformed
        // TODO add your handling code here:
        jEditBtn.setEnabled(false);
        jButton1.setEnabled(true);
        disableFields(true);


    }//GEN-LAST:event_jEditBtnActionPerformed

    private void jNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jNameKeyPressed
        // TODO add your handling code here:
//        if(jName.getText().matches("^([a-zA-Z])")){
//            jPhoneValidation.setText("");
//        }
//        else{
//            jPhoneValidation.setText("Invalid Name");
//
//        }
    }//GEN-LAST:event_jNameKeyPressed

    private void jPhoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPhoneKeyPressed
        // TODO add your handling code here:
//        if(jPhone.getText().matches("^[0-9]{10}$")){
//            jPhoneValidation.setText("");
//
//        }
//        else{
//            jPhoneValidation.setText("Invalid Phone Number");
//        }
    }//GEN-LAST:event_jPhoneKeyPressed

    private void jEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jEmailKeyPressed
        // TODO add your handling code here:
//        if(!jEmail.getText().matches("^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$")){
//            jEmailValidation.setText("Invalid Email");
//        }
//        else{
//            jEmailValidation.setText("");
//        }
    }//GEN-LAST:event_jEmailKeyPressed

    private void jPhoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPhoneKeyReleased
        // TODO add your handling code here:
        String pattern = "^[0-9]{10}$";
        Pattern pat = Pattern.compile(pattern);
        Matcher mat = pat.matcher(jPhone.getText());
        if(!mat.matches()){
            jLabel13.setText("cell no. is incorrect");
        }
        else{
            jLabel13.setText(null);
        }
    }//GEN-LAST:event_jPhoneKeyReleased

    private void jEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jEmailKeyReleased
        // TODO add your handling code here:
        String pattern = "^[a-zA-Z0-9._]{0,30}[@][a-zA-Z0-9]{0,10}[.][a-zA-Z]{2,5}$";
        Pattern pat = Pattern.compile(pattern);
        Matcher mat = pat.matcher(jEmail.getText());
        if(!mat.matches()){
            jLabel12.setText("Email is incorrect");
        }
        else{
            jLabel12.setText(null);
        }
    }//GEN-LAST:event_jEmailKeyReleased
    void disableFields(boolean flag){
        jId.setEnabled(flag);
        jName.setEnabled(flag);
        jPhone.setEnabled(flag);
        jEmail.setEnabled(flag);
        jDateChooser1.setEnabled(flag);
        jStreetNumber.setEnabled(flag);
        jZipCode.setEnabled(flag);
        jAptNumber.setEnabled(flag);
        jCityName.setEnabled(flag);
        jGender.setEditable(flag);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jAptNumber;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jCityName;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JButton jEditBtn;
    private javax.swing.JTextField jEmail;
    private javax.swing.JComboBox<String> jGender;
    private javax.swing.JTextField jId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jName;
    private javax.swing.JTextField jPhone;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jStreetNumber;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jZipCode;
    // End of variables declaration//GEN-END:variables
}
