/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Admin;

import ComEnterprise.City;
import ComEnterprise.CityCatalouge;
import ComEnterprise.House;
import ComEnterprise.LoginInfo;
import ComEnterprise.People;
import ComEnterprise.PeopleCatalouge;
import UserInterface.Community.CommunityAdmin;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSplitPane;


/**
 *
 * @author namithajc
 */
public class PeopleDetails extends javax.swing.JPanel {

    /**
     * Creates new form AddCommunity
     */
   
    JSplitPane jSplitPane2;
    City selectedCity;
    JPanel jPanel2;
    boolean isView;
    CityCatalouge cityLog;
    People p;
    String selectedComm;
    public PeopleDetails( City selectedCity, JSplitPane jSplitPane2, String selectedCity1, JPanel jPanel2, boolean isView, CityCatalouge cityLog, People p, String selectedComm) {
        initComponents();
        this.jSplitPane2 = jSplitPane2; 
        this.selectedCity = selectedCity;
        this.jPanel2 = jPanel2; 
        this.isView = isView;
        this.cityLog = cityLog;
        this.p = p;
        this.selectedComm = selectedComm;
        for (int i = 0; i< selectedCity.getCommunityCatalog().size();i++){
            jCommunity.addItem(selectedCity.getCommunityCatalog().get(i).getCommunityName());
        }
        if(!isView){
            jEditBtn.setVisible(false);
            jSave.setVisible(false);
        }
        if(isView){
            jCommunity.setEnabled(false);
            disableFields(false);
            jButton3.setVisible(false);
            jEditBtn.setVisible(true);
            jCommunity.setSelectedItem(selectedComm);
            jCommunity.setEditable(false);
            jDateChooser1.setEnabled(false);
            jGender.setEnabled(false);
            jGender.setSelectedItem(p.getGender());
                        jId.setText(p.getId());
                        jName.setText(p.getName());
                        jPhone.setText(p.getPhone());
                        jEmail.setText(p.getEmail());
                        jDateChooser1.setDate(p.getDob());
                        jStreetNumber.setText(p.getHouse().getStreetName());
                        jZipCode.setText(p.getHouse().getZipCode());
                        jAptNumber.setText(p.getHouse().getApartementNo());
                       
                    }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPhone = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jAptNumber = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jId = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jStreetNumber = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jZipCode = new javax.swing.JTextField();
        jSave = new javax.swing.JButton();
        jEditBtn = new javax.swing.JButton();
        jGender = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jCommunity = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setBackground(new java.awt.Color(170, 185, 207));
        setPreferredSize(new java.awt.Dimension(800, 500));

        jLabel2.setFont(new java.awt.Font("Lava Kannada", 1, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLabel3.setText("Name:");

        jName.setBackground(new java.awt.Color(247, 247, 255));
        jName.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNameActionPerformed(evt);
            }
        });
        jName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jNameKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLabel4.setText("Gender:");

        jLabel5.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLabel5.setText("Dob:");

        jLabel6.setBackground(new java.awt.Color(247, 247, 255));
        jLabel6.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLabel6.setText("Email:");

        jEmail.setBackground(new java.awt.Color(247, 247, 255));
        jEmail.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jEmailKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jEmailKeyReleased(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(247, 247, 255));
        jLabel7.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLabel7.setText("Phone:");

        jPhone.setBackground(new java.awt.Color(247, 247, 255));
        jPhone.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPhoneActionPerformed(evt);
            }
        });
        jPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPhoneKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPhoneKeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLabel8.setText("Apt No:");

        jAptNumber.setBackground(new java.awt.Color(247, 247, 255));
        jAptNumber.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jAptNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAptNumberActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLabel9.setText("ID:");

        jId.setBackground(new java.awt.Color(247, 247, 255));
        jId.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIdActionPerformed(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(247, 247, 255));
        jLabel10.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLabel10.setText("St Name:");

        jStreetNumber.setBackground(new java.awt.Color(247, 247, 255));
        jStreetNumber.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N

        jLabel11.setBackground(new java.awt.Color(247, 247, 255));
        jLabel11.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLabel11.setText("ZipCode:");

        jZipCode.setBackground(new java.awt.Color(247, 247, 255));
        jZipCode.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jZipCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jZipCodeActionPerformed(evt);
            }
        });

        jSave.setBackground(new java.awt.Color(247, 247, 255));
        jSave.setFont(new java.awt.Font("Lava Kannada", 0, 12)); // NOI18N
        jSave.setText("Save");
        jSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaveActionPerformed(evt);
            }
        });

        jEditBtn.setBackground(new java.awt.Color(247, 247, 255));
        jEditBtn.setFont(new java.awt.Font("Lava Kannada", 0, 12)); // NOI18N
        jEditBtn.setText("Edit");
        jEditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEditBtnActionPerformed(evt);
            }
        });

        jGender.setBackground(new java.awt.Color(247, 247, 255));
        jGender.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGenderActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLabel1.setText("Community:");

        jButton3.setBackground(new java.awt.Color(247, 247, 255));
        jButton3.setFont(new java.awt.Font("Lava Kannada", 0, 12)); // NOI18N
        jButton3.setText("Submit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jCommunity.setBackground(new java.awt.Color(247, 247, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jAptNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(89, 89, 89)
                        .addComponent(jSave)
                        .addGap(249, 249, 249))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jId, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jName, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addComponent(jGender, 0, 164, Short.MAX_VALUE)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6))
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPhone)
                            .addComponent(jEmail)
                            .addComponent(jZipCode)
                            .addComponent(jStreetNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(74, 74, 74))))
            .addGroup(layout.createSequentialGroup()
                .addGap(371, 371, 371)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jEditBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel9)
                            .addComponent(jId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel10)
                            .addComponent(jStreetNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jAptNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSave)
                    .addComponent(jEditBtn)
                    .addComponent(jButton3))
                .addGap(82, 82, 82))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveActionPerformed
//         TODO add your handling code here:
        boolean isPresent = false;
        PeopleCatalouge pepLog = selectedCity.getCommunityCatalog().searchCommunity(selectedComm).getPeopleCatalog();
        String name = jName.getText();
        String id = jId.getText();
        Date dob = jDateChooser1.getDate();
        String gender = (String) jGender.getSelectedItem();
        String phoneNo = jPhone.getText();
        String email = jEmail.getText();
        String aptNo = jAptNumber.getText();
        String streetNo = jStreetNumber.getText();
        String zipCode = jZipCode.getText();
 
        if(name.trim().length() == 0 ||id.trim().length() == 0|| gender.trim().length() == 0 || phoneNo.trim().length() == 0|| email.trim().length() == 0 || aptNo.trim().length() == 0 || streetNo.trim().length() == 0|| zipCode.trim().length() ==0 ){
            JOptionPane.showMessageDialog(this, "All Fields must be entered");
        }
        else{
                p.setDob(dob);
                p.setName(name);
                p.setGender(gender);
                p.setPhone(phoneNo);
                p.setId(id);
                p.setEmail(email);
                p.setCommunityAdmin(true);
                p.setHouse(new House(aptNo,streetNo,zipCode));
                p.setLoginInfo(new LoginInfo("","")); 
                 CommunityAdmin commAdmin = new CommunityAdmin(cityLog,jSplitPane2,selectedCity.getCommunityCatalog().searchCommunity(selectedComm), jPanel2,selectedCity,false);
                jSplitPane2.setRightComponent(commAdmin);
          
        }
            
     
       
    }//GEN-LAST:event_jSaveActionPerformed

    private void jEditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEditBtnActionPerformed
        // TODO add your handling code here:
        jEditBtn.setEnabled(false);
        jSave.setEnabled(true);
        disableFields(true);
        jId.setEnabled(false);
        jGender.setEnabled(true);


    }//GEN-LAST:event_jEditBtnActionPerformed

    private void jNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jNameKeyPressed
        // TODO add your handling code here:
//        if(jName.getText().matches("^([a-zA-Z])")){
//            jPhoneValidation.setText("");
//        }
//        else{
//            jPhoneValidation.setText("Invalid Name");
//
//        }
    }//GEN-LAST:event_jNameKeyPressed

    private void jPhoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPhoneKeyPressed
        // TODO add your handling code here:
//        if(jPhone.getText().matches("^[0-9]{10}$")){
//            jPhoneValidation.setText("");
//
//        }
//        else{
//            jPhoneValidation.setText("Invalid Phone Number");
//        }
    }//GEN-LAST:event_jPhoneKeyPressed

    private void jEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jEmailKeyPressed
        // TODO add your handling code here:
//        if(!jEmail.getText().matches("^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$")){
//            jEmailValidation.setText("Invalid Email");
//        }
//        else{
//            jEmailValidation.setText("");
//        }
    }//GEN-LAST:event_jEmailKeyPressed

    private void jNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNameActionPerformed

    private void jAptNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAptNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAptNumberActionPerformed

    private void jPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPhoneActionPerformed

    private void jIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jIdActionPerformed

    private void jZipCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jZipCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jZipCodeActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        boolean isPresent = false;
        String selectedComm = (String) jCommunity.getSelectedItem();
        PeopleCatalouge pepLog = selectedCity.getCommunityCatalog().searchCommunity(selectedComm).getPeopleCatalog();
        String name = jName.getText();
        String id = jId.getText();
        Date dob = jDateChooser1.getDate();
        String gender = (String) jGender.getSelectedItem();
        String phoneNo = jPhone.getText();
        String email = jEmail.getText();
        String aptNo = jAptNumber.getText();
        String streetNo = jStreetNumber.getText();
        String zipCode = jZipCode.getText();
        
        
        if(name.trim().length() == 0 ||id.trim().length() == 0|| gender.trim().length() == 0 || phoneNo.trim().length() == 0|| email.trim().length() == 0 || aptNo.trim().length() == 0 || streetNo.trim().length() == 0|| zipCode.trim().length() ==0 ){
            JOptionPane.showMessageDialog(this, "All Fields must be entered");
        }
        else{
          boolean exists = pepLog.personPresent(id);
            if(exists){
                JOptionPane.showMessageDialog(this, "Person with the ID already exists"); 
            }
            else{
               p.setDob(dob);
                p.setName(name);
                p.setGender(gender);
                p.setPhone(phoneNo);
                p.setId(id);
                p.setEmail(email);
                p.setCommunityAdmin(true);
                p.setHouse(new House(aptNo,streetNo,zipCode));
                p.setLoginInfo(new LoginInfo("",""));
                pepLog.addPeople(p);
                CommunityAdmin commAdmin = new CommunityAdmin(cityLog,jSplitPane2,selectedCity.getCommunityCatalog().searchCommunity(selectedComm), jPanel2,selectedCity,false);
                jSplitPane2.setRightComponent(commAdmin);  
            }  
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jGenderActionPerformed

    private void jPhoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPhoneKeyReleased
        // TODO add your handling code here:
        String pattern = "^[0-9]{10}$";
        Pattern pat = Pattern.compile(pattern);
        Matcher mat = pat.matcher(jPhone.getText());
        if(!mat.matches()){
            jLabel12.setText("cell no. is incorrect");
        }
        else{
            jLabel12.setText(null);
        }
    }//GEN-LAST:event_jPhoneKeyReleased

    private void jEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jEmailKeyReleased
        // TODO add your handling code here:
        String pattern = "^[a-zA-Z0-9._]{0,30}[@][a-zA-Z0-9]{0,10}[.][a-zA-Z]{2,5}$";
        Pattern pat = Pattern.compile(pattern);
        Matcher mat = pat.matcher(jEmail.getText());
        if(!mat.matches()){
            jLabel13.setText("Email is incorrect");
        }
        else{
            jLabel13.setText(null);
        }
    }//GEN-LAST:event_jEmailKeyReleased
    void disableFields(boolean flag){
        jId.setEnabled(flag);
        jName.setEnabled(flag);
        jPhone.setEnabled(flag);
        jEmail.setEnabled(flag);
        jDateChooser1.setEnabled(flag);
        jStreetNumber.setEnabled(flag);
        jZipCode.setEnabled(flag);
        jAptNumber.setEnabled(flag);
        jGender.setEditable(flag);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jAptNumber;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jCommunity;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JButton jEditBtn;
    private javax.swing.JTextField jEmail;
    private javax.swing.JComboBox<String> jGender;
    private javax.swing.JTextField jId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jName;
    private javax.swing.JTextField jPhone;
    private javax.swing.JButton jSave;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jStreetNumber;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jZipCode;
    // End of variables declaration//GEN-END:variables
}
