/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Hopsital;

import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSplitPane;
import HospitalEnterprise.AppointmentsCatalouge;
import ComEnterprise.CityCatalouge;
import ComEnterprise.Community;
import HospitalEnterprise.Doctor;
import HospitalEnterprise.EncounterHistory;
import HospitalEnterprise.Hospital;
import ComEnterprise.House;
import ComEnterprise.LoginInfo;
import HospitalEnterprise.PatientCatalouge;
import ComEnterprise.People;
import ComEnterprise.PeopleCatalouge;

/**
 *
 * @author namithajc
 */
public class AddPatient extends javax.swing.JPanel {

    /**
     * Creates new form AddPatient
     */
    JSplitPane jSplitPane1;
    JSplitPane patientPane;
    Hospital hosp;
    boolean isView;
    Community comm;
    JPanel mainPane;
    JPanel patientPane1;
    People selectedPerson;
    CityCatalouge cityLog;
    public AddPatient(JSplitPane jSplitPane1, JSplitPane patientPane, Hospital hosp, Community comm, boolean isView, JPanel mainPane, JPanel patientPane1,People selectedPerson,CityCatalouge cityLog) {
        initComponents();
        this.jSplitPane1 = jSplitPane1;
        this.hosp = hosp;
        this.isView = isView;
        this.comm = comm;
        this.mainPane = mainPane;
        this.patientPane1 = patientPane1;
        this.selectedPerson = selectedPerson;
        this.cityLog = cityLog;
        if(!isView){
            jEdit.setEnabled(false);
        }
        if(isView){
            jId.setText(selectedPerson.getId());
            populatecontents(selectedPerson);
            disableFields(false);
            jId.setEnabled(false);
            jEdit.setEnabled(true);
            jButton2.setEnabled(false);
            jButton1.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jStNo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jZip = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPhone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jAptNo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jEdit = new javax.swing.JButton();
        jId = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(170, 185, 207));

        jStNo.setBackground(new java.awt.Color(247, 247, 255));
        jStNo.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLabel2.setText("Name:");

        jZip.setBackground(new java.awt.Color(247, 247, 255));
        jZip.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLabel3.setText("Dob:");

        jName.setBackground(new java.awt.Color(247, 247, 255));
        jName.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLabel4.setText("Phone:");

        jPhone.setBackground(new java.awt.Color(247, 247, 255));
        jPhone.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLabel5.setText("Gender:");

        jEmail.setBackground(new java.awt.Color(247, 247, 255));
        jEmail.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLabel6.setText("Email:");

        jAptNo.setBackground(new java.awt.Color(247, 247, 255));
        jAptNo.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLabel7.setText("Street No:");

        jButton1.setBackground(new java.awt.Color(247, 247, 255));
        jButton1.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLabel8.setText("Apt No:");

        jButton2.setBackground(new java.awt.Color(247, 247, 255));
        jButton2.setFont(new java.awt.Font("Lava Kannada", 0, 12)); // NOI18N
        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLabel9.setText("Zip-Code:");

        jEdit.setBackground(new java.awt.Color(247, 247, 255));
        jEdit.setFont(new java.awt.Font("Lava Kannada", 0, 12)); // NOI18N
        jEdit.setText("Edit");
        jEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEditActionPerformed(evt);
            }
        });

        jId.setBackground(new java.awt.Color(247, 247, 255));
        jId.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N

        jComboBox1.setBackground(new java.awt.Color(247, 247, 255));
        jComboBox1.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        jDateChooser1.setBackground(new java.awt.Color(247, 247, 255));

        jLabel1.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLabel1.setText("ID:");

        jLabel10.setFont(new java.awt.Font("Lava Kannada", 1, 14)); // NOI18N
        jLabel10.setText("Patient Details");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jStNo)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jId, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jZip, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 188, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPhone)
                    .addComponent(jEmail)
                    .addComponent(jAptNo)
                    .addComponent(jName, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(344, 344, 344))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2)
                            .addComponent(jEdit))
                        .addGap(322, 322, 322))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel10)
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel1)
                            .addComponent(jId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel3)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel5)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel7)
                            .addComponent(jStNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel9)
                            .addComponent(jZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel2)
                            .addComponent(jName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel4)
                            .addComponent(jPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel6)
                            .addComponent(jEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel8)
                            .addComponent(jAptNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jEdit)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(47, 47, 47))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String id = jId.getText();
        PeopleCatalouge peopLog = comm.getPeopleCatalog();
        for(int i = 0 ;i < peopLog.size();i++){
            People p = peopLog.get(i);
            if(p.getId().equals(id)){
                populatecontents(p);
                disableFields(false);
                break;
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        boolean isPresent = false;
        String id = jId.getText();
        String name = jName.getText();
        String email =jEmail.getText();
        String phone =jPhone.getText();
        Date dob = jDateChooser1.getDate();
        String gender = (String) jComboBox1.getSelectedItem();
        String streetNo = jStNo.getText();
        String aptNo = jAptNo.getText();
        String zipCode = jZip.getText();
        String temp[] = jDateChooser1.getDate().toString().split(" ");
        int length = temp.length;
        String dobYear = temp[length-1];
        PeopleCatalouge peopLog = comm.getPeopleCatalog();
        if(name.trim().length() == 0 ||id.trim().length() == 0|| gender.trim().length() == 0 || phone.trim().length() == 0|| email.trim().length() == 0 || aptNo.trim().length() == 0 || streetNo.trim().length() == 0|| zipCode.trim().length() ==0 ){
            JOptionPane.showMessageDialog(this, "All Fields must be entered");
        }
        if(isView){
            selectedPerson.setDob(dob);
            selectedPerson.setName(name);
            selectedPerson.setEmail(email);
            selectedPerson.setGender(gender);
            selectedPerson.setPhone(phone);
            selectedPerson.setId(id);
            selectedPerson.setHouse(new House(aptNo,streetNo,zipCode));
        }
        else{
            for(int i = 0 ;i < peopLog.size();i++){
                People p = peopLog.get(i);
                if(p.getId().equals(id)){
                    p.setDob(dob);
                    p.setName(name);
                    p.setDoctor(true);
                    p.setEmail(email);
                    p.setGender(gender);
                    p.setPhone(phone);
                    p.setId(id);
                    p.setHouse(new House(aptNo,streetNo,zipCode));
                    p.setEncounterHistory(new EncounterHistory());
                    p.setLoginInfo(new LoginInfo("",""));
                    boolean ifExists = hosp.getPatientCatalouge().checkExisting(id);
                    if(ifExists){
                        JOptionPane.showMessageDialog(this, "Patient with Id already exists");
                    }
                    else{
                    hosp.getPatientCatalouge().addPatient(p);
                    }
                    isPresent = true;
                    break;
                }
            }
            if(!isPresent){
                People newPerson = new People();
                newPerson.setDob(dob);
                newPerson.setName(name);
                newPerson.setEmail(email);
                newPerson.setGender(gender);
                newPerson.setPhone(phone);
                newPerson.setId(id);
                newPerson.setHouse(new House(aptNo,streetNo,zipCode));
                newPerson.setLoginInfo(new LoginInfo("",""));
                newPerson.setEncounterHistory(new EncounterHistory());
                Doctor doc = new Doctor();
                boolean ifExists = hosp.getPatientCatalouge().checkExisting(id);
                if(ifExists){
                        JOptionPane.showMessageDialog(this, "Patient with Id already exists");
                    }
                    else{
                        hosp.getPatientCatalouge().addPatient(newPerson);

                    }
            }
        }
        HospitalAdmin hA = new HospitalAdmin(jSplitPane1,mainPane,comm, hosp,true);
        jSplitPane1.setRightComponent(hA);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEditActionPerformed
        // TODO add your handling code here:
        disableFields(true);
        jEdit.setEnabled(false);
        jButton2.setEnabled(true);
    }//GEN-LAST:event_jEditActionPerformed

    void disableFields(boolean flag){
        jName.setEnabled(flag);
        jEmail.setEnabled(flag);
        jPhone.setEnabled(flag);
        jDateChooser1.setEnabled(flag);
        jComboBox1.setEnabled(flag);
        jStNo.setEnabled(flag);
        jAptNo.setEnabled(flag);
        jZip.setEnabled(flag);
    }
    void populatecontents(People p){
                jName.setText(p.getName());
                jEmail.setText(p.getEmail());
                jPhone.setText(p.getPhone());
                jDateChooser1.setDate(p.getDob());
                jComboBox1.setSelectedItem(p.getGender());
                jStNo.setText(p.getHouse().getStreetName());
                jAptNo.setText(p.getHouse().getApartementNo());
                jZip.setText(p.getHouse().getZipCode());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jAptNo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JButton jEdit;
    private javax.swing.JTextField jEmail;
    private javax.swing.JTextField jId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jName;
    private javax.swing.JTextField jPhone;
    private javax.swing.JTextField jStNo;
    private javax.swing.JTextField jZip;
    // End of variables declaration//GEN-END:variables
}
