/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Hopsital;

import ComEnterprise.Community;
import ComEnterprise.House;
import ComEnterprise.LoginInfo;
import ComEnterprise.People;
import ComEnterprise.PeopleCatalouge;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSplitPane;
import HospitalEnterprise.AppointmentsCatalouge;
import HospitalEnterprise.Doctor;
import HospitalEnterprise.Hospital;
import HospitalEnterprise.PatientCatalouge;


/**
 *
 * @author namithajc
 */
public class DoctorDetails extends javax.swing.JPanel {

    /**
     * Creates new form doctorDetails
     */
    JSplitPane jSplitPane1;
    Hospital hosp;
    boolean isView;
    Community comm;
    JPanel jPanel2;
    Doctor selectedDoctor;
    public DoctorDetails(JSplitPane jSplitPane1, Hospital hosp, Community comm, boolean isView, JPanel jPanel2, Doctor selectedDoctor) {
        initComponents();
        this.jSplitPane1 = jSplitPane1;
        this.hosp = hosp;
        this.isView = isView;
        this.comm = comm;
        this.jPanel2 = jPanel2;
        this.selectedDoctor = selectedDoctor;
        if(!isView){
            jEdit.setEnabled(false);
        }
        if(isView){
            jId.setText(selectedDoctor.getPerson().getId());
            jSpec.setText(selectedDoctor.getSpecialization());
            populatecontents(selectedDoctor.getPerson());
            disableFields(false);
            jId.setEnabled(false);
            jSpec.setEnabled(false);
            jEdit.setEnabled(true);
            jButton2.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jId = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jStNo = new javax.swing.JTextField();
        jZip = new javax.swing.JTextField();
        jName = new javax.swing.JTextField();
        jPhone = new javax.swing.JTextField();
        jEmail = new javax.swing.JTextField();
        jAptNo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jEdit = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jSpec = new javax.swing.JTextField();

        setBackground(new java.awt.Color(170, 185, 207));

        jLabel1.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLabel1.setText("ID:");

        jLabel2.setBackground(new java.awt.Color(247, 247, 255));
        jLabel2.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLabel2.setText("Name:");

        jLabel3.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLabel3.setText("Dob:");

        jLabel4.setBackground(new java.awt.Color(247, 247, 255));
        jLabel4.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLabel4.setText("Phone:");

        jLabel5.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLabel5.setText("Gender:");

        jLabel6.setBackground(new java.awt.Color(247, 247, 255));
        jLabel6.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLabel6.setText("Email:");

        jLabel7.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLabel7.setText("Street No:");

        jLabel8.setBackground(new java.awt.Color(247, 247, 255));
        jLabel8.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLabel8.setText("Apt No:");

        jLabel9.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLabel9.setText("Zip-Code:");

        jId.setBackground(new java.awt.Color(247, 247, 255));
        jId.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N

        jDateChooser1.setBackground(new java.awt.Color(247, 247, 255));

        jStNo.setBackground(new java.awt.Color(247, 247, 255));
        jStNo.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N

        jZip.setBackground(new java.awt.Color(247, 247, 255));
        jZip.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N

        jName.setBackground(new java.awt.Color(247, 247, 255));
        jName.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N

        jPhone.setBackground(new java.awt.Color(247, 247, 255));
        jPhone.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N

        jEmail.setBackground(new java.awt.Color(247, 247, 255));
        jEmail.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N

        jAptNo.setBackground(new java.awt.Color(247, 247, 255));
        jAptNo.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N

        jButton1.setBackground(new java.awt.Color(247, 247, 255));
        jButton1.setFont(new java.awt.Font("Lava Kannada", 0, 12)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(247, 247, 255));
        jButton2.setFont(new java.awt.Font("Lava Kannada", 0, 12)); // NOI18N
        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jEdit.setBackground(new java.awt.Color(247, 247, 255));
        jEdit.setFont(new java.awt.Font("Lava Kannada", 0, 12)); // NOI18N
        jEdit.setText("Edit");
        jEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEditActionPerformed(evt);
            }
        });

        jComboBox1.setBackground(new java.awt.Color(247, 247, 255));
        jComboBox1.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        jLabel10.setBackground(new java.awt.Color(247, 247, 255));
        jLabel10.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLabel10.setText("Specialization:");

        jSpec.setBackground(new java.awt.Color(247, 247, 255));
        jSpec.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jStNo)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(jId, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jZip))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPhone)
                    .addComponent(jEmail)
                    .addComponent(jAptNo)
                    .addComponent(jName)
                    .addComponent(jSpec, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                .addGap(97, 97, 97))
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(jEdit)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(jId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel10)
                    .addComponent(jSpec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel7)
                    .addComponent(jStNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel9)
                    .addComponent(jZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAptNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jEdit))
                .addContainerGap(44, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String id = jId.getText();
        PeopleCatalouge peopLog = comm.getPeopleCatalog();
        for(int i = 0 ;i < peopLog.size();i++){
            People p = peopLog.get(i);
            if(p.getId().equals(id)){
                populatecontents(p);
                disableFields(false);
                break;
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        boolean isPresent = false;
        String id = jId.getText();
        String spec = jSpec.getText();
        String name = jName.getText();
        String email =jEmail.getText();
        String phone =jPhone.getText();
        Date dob = jDateChooser1.getDate();
        String gender = (String) jComboBox1.getSelectedItem();
        String streetNo = jStNo.getText();
        String aptNo = jAptNo.getText();
        String zipCode = jZip.getText();
        String temp[] = jDateChooser1.getDate().toString().split(" ");
        int length = temp.length;
        String dobYear = temp[length-1];
        PeopleCatalouge peopLog = comm.getPeopleCatalog();
        if(name.trim().length() == 0 ||id.trim().length() == 0|| gender.trim().length() == 0 || phone.trim().length() == 0|| email.trim().length() == 0 || aptNo.trim().length() == 0 || streetNo.trim().length() == 0|| zipCode.trim().length() ==0 ){
        JOptionPane.showMessageDialog(this, "All Fields must be entered");
        }
        boolean exists = hosp.getDoctorCataloug().isPresentDoctor(id);
        if(exists && !isView){
            JOptionPane.showMessageDialog(this, "Doctor Under the Id already exists");
            disableFields(true);
        }
        else{  
        if(isView){
            selectedDoctor.setSpecialization(spec);
            selectedDoctor.getPerson().setDob(dob);
            selectedDoctor.getPerson().setName(name);
            selectedDoctor.getPerson().setEmail(email);
            selectedDoctor.getPerson().setGender(gender);
            selectedDoctor.getPerson().setPhone(phone);
            selectedDoctor.getPerson().setId(id);
            selectedDoctor.getPerson().setHouse(new House(aptNo,streetNo,zipCode)); 
        }
        else{      
        for(int i = 0 ;i < peopLog.size();i++){
            People p = peopLog.get(i);
            if(p.getId().equals(id)){   
            p.setDob(dob);
            p.setName(name);
            p.setDoctor(true);
            p.setEmail(email);
            p.setGender(gender);
            p.setPhone(phone);
            p.setId(id);
            p.setHouse(new House(aptNo,streetNo,zipCode));
            p.setDoctor(true);
            p.setLoginInfo(new LoginInfo(p.getName().replaceAll("\\s", "")+id,p.getName().substring(0,3)+dobYear)); 
               Doctor d =new Doctor();
               d.setSpecialization(spec);
               d.setPerson(p);
               d.setAppointmentCatalouge(new AppointmentsCatalouge());
               d.setPatientCatalouge(new PatientCatalouge());
               hosp.getDoctorCataloug().addDoctor(d);
               isPresent = true;
               break;
            }
        }
        if(!isPresent){
                People newPerson = new People();
                newPerson.setDob(dob);
                newPerson.setName(name);
                newPerson.setDoctor(true);
                newPerson.setEmail(email);
                newPerson.setGender(gender);
                newPerson.setPhone(phone);
                newPerson.setId(id);
                newPerson.setHouse(new House(aptNo,streetNo,zipCode));
                newPerson.setLoginInfo(new LoginInfo(name.replaceAll("\\s", "")+id,name.substring(0,3)+dobYear));
                Doctor doc = new Doctor();
                doc.setPerson(newPerson);
                doc.setSpecialization(spec);
                doc.setAppointmentCatalouge(new AppointmentsCatalouge());
                doc.setPatientCatalouge(new PatientCatalouge());
                hosp.getDoctorCataloug().addDoctor(doc);
            }
        }
        HospitalAdmin hA = new HospitalAdmin(jSplitPane1,jPanel2,comm, hosp,false);
        jSplitPane1.setRightComponent(hA);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEditActionPerformed
        // TODO add your handling code here:
        disableFields(true);
        jEdit.setEnabled(false);
        jButton2.setEnabled(true);
        jSpec.setEnabled(true); 

    }//GEN-LAST:event_jEditActionPerformed

    void populatecontents(People p){
                jName.setText(p.getName());
                jEmail.setText(p.getEmail());
                jPhone.setText(p.getPhone());
                jDateChooser1.setDate(p.getDob());
                jComboBox1.setSelectedItem(p.getGender());
                jStNo.setText(p.getHouse().getStreetName());
                jAptNo.setText(p.getHouse().getApartementNo());
                jZip.setText(p.getHouse().getZipCode());
    }
    
    void disableFields(boolean flag){
        jName.setEnabled(flag);
        jEmail.setEnabled(flag);
        jPhone.setEnabled(flag);
        jDateChooser1.setEnabled(flag);
        jComboBox1.setEnabled(flag);
        jStNo.setEnabled(flag);
        jAptNo.setEnabled(flag);
        jZip.setEnabled(flag);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jAptNo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JButton jEdit;
    private javax.swing.JTextField jEmail;
    private javax.swing.JTextField jId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jName;
    private javax.swing.JTextField jPhone;
    private javax.swing.JTextField jSpec;
    private javax.swing.JTextField jStNo;
    private javax.swing.JTextField jZip;
    // End of variables declaration//GEN-END:variables
}
