/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Hopsital;

import static java.lang.String.valueOf;
import java.time.Instant;
import java.time.LocalDate;
import java.time.Period;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JSplitPane;
import javax.swing.table.DefaultTableModel;
import HospitalEnterprise.Appointments;
import HospitalEnterprise.AppointmentsCatalouge;
import ComEnterprise.City;
import ComEnterprise.CityCatalouge;
import ComEnterprise.Community;
import HospitalEnterprise.Doctor;
import HospitalEnterprise.DoctorCatalouge;
import HospitalEnterprise.Hospital;
import ComEnterprise.House;
import ComEnterprise.LoginInfo;
import ComEnterprise.People;
import ComEnterprise.PeopleCatalouge;

/**
 *
 * @author namithajc
 */
public class EditPatientDetails extends javax.swing.JPanel {

    /**
     * Creates new form BookAppointment
     */
    JSplitPane jSplitPane2;
    CityCatalouge cityLog;
    DoctorCatalouge doctor;
    PeopleCatalouge peopleCatalog;
    String beforeEditcity;
    String beforeEditComm;
    //Patient selectedPatient;
    People p;
    Community comm1;
    public EditPatientDetails(JSplitPane jSplitPane2, People p, Community comm, CityCatalouge cityLog) {
        initComponents();
        jDateChooser2.getJCalendar().setMinSelectableDate(new Date());
        this.cityLog = cityLog;
        this.p = p;
        this.comm1 = comm;
        this.jSplitPane2 = jSplitPane2;
        this.peopleCatalog = peopleCatalog;
        LocalDate curDate = LocalDate.now();
        Instant instant = p.getDob().toInstant();
        ZonedDateTime zone = instant.atZone(ZoneId.systemDefault());
        LocalDate givenDate = zone.toLocalDate();
            int age  = Period.between(givenDate,curDate).getYears();
        //jTSelectDoc.setText(selDoctor.getPerson().getName());
        //jTSelectDoc.setEditable(false);
        //disableTextFields();
        jId.setText(p.getId());
        jPatientName.setText(p.getName());
        jPatientEmail.setText(p.getEmail());
        jPatientPhoneNo.setText(p.getPhone());
        jApt.setText(p.getHouse().getApartementNo());
        jSt.setText(p.getHouse().getStreetName());
        jZip.setText(p.getHouse().getZipCode());
        jDateChooser2.setDate(p.getDob());
        jTPatientAge.setText(valueOf(age));
         jComboBox1.setSelectedItem(p.getGender());
         for(int i = 0; i < cityLog.size();i++){
             jComboBox2.addItem(cityLog.get(i).getCityName());
         }
         
        jTPatientAge.setEnabled(false);
        jId.setEnabled(false);
        jPatientName.setEnabled(false);
        jPatientEmail.setEnabled(false);
        jPatientPhoneNo.setEnabled(false);
        jDateChooser2.setEnabled(false);
         jComboBox1.setEnabled(false);
         jButton4.setVisible(false);
         jApt.setEnabled(false);
        jSt.setEnabled(false);
        jZip.setEnabled(false);
        

    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPatientPhoneNo = new javax.swing.JTextField();
        jLPatName = new javax.swing.JLabel();
        jLPatDob = new javax.swing.JLabel();
        jLPatAge = new javax.swing.JLabel();
        jLPatGender = new javax.swing.JLabel();
        jLPatPhone = new javax.swing.JLabel();
        jPatientName = new javax.swing.JTextField();
        jTPatientAge = new javax.swing.JTextField();
        jPatientEmail = new javax.swing.JTextField();
        jLPatEmail = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jId = new javax.swing.JTextField();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jSt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jApt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jZip = new javax.swing.JTextField();

        jLabel5.setText("jLabel5");

        setBackground(new java.awt.Color(170, 185, 207));

        jLabel1.setFont(new java.awt.Font("Lava Kannada", 1, 14)); // NOI18N
        jLabel1.setText("Patient Details");

        jPatientPhoneNo.setBackground(new java.awt.Color(247, 247, 255));
        jPatientPhoneNo.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jPatientPhoneNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPatientPhoneNoActionPerformed(evt);
            }
        });

        jLPatName.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLPatName.setText("Name:");

        jLPatDob.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLPatDob.setText("Date Of Birth:");

        jLPatAge.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLPatAge.setText("Age:");

        jLPatGender.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLPatGender.setText("Gender:");

        jLPatPhone.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLPatPhone.setText("Phone:");

        jPatientName.setBackground(new java.awt.Color(247, 247, 255));
        jPatientName.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jPatientName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPatientNameActionPerformed(evt);
            }
        });

        jTPatientAge.setBackground(new java.awt.Color(247, 247, 255));
        jTPatientAge.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jTPatientAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTPatientAgeActionPerformed(evt);
            }
        });

        jPatientEmail.setBackground(new java.awt.Color(247, 247, 255));
        jPatientEmail.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jPatientEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPatientEmailActionPerformed(evt);
            }
        });

        jLPatEmail.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLPatEmail.setText("Email:");

        jLabel3.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLabel3.setText("ID:");

        jId.setBackground(new java.awt.Color(247, 247, 255));
        jId.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIdActionPerformed(evt);
            }
        });

        jDateChooser2.setBackground(new java.awt.Color(247, 247, 255));

        jButton4.setBackground(new java.awt.Color(247, 247, 255));
        jButton4.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jButton4.setText("Register");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(247, 247, 255));
        jButton5.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jButton5.setText("Save");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(247, 247, 255));
        jButton6.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jButton6.setText("Edit");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jComboBox1.setBackground(new java.awt.Color(247, 247, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        jLabel2.setBackground(new java.awt.Color(247, 247, 255));
        jLabel2.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLabel2.setText("City:");

        jComboBox2.setBackground(new java.awt.Color(247, 247, 255));
        jComboBox2.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(247, 247, 255));
        jLabel4.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLabel4.setText("Community:");

        jComboBox3.setBackground(new java.awt.Color(247, 247, 255));
        jComboBox3.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(247, 247, 255));
        jLabel6.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLabel6.setText("St Name:");

        jSt.setBackground(new java.awt.Color(247, 247, 255));
        jSt.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N

        jLabel7.setBackground(new java.awt.Color(247, 247, 255));
        jLabel7.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLabel7.setText("AptNo:");

        jApt.setBackground(new java.awt.Color(247, 247, 255));
        jApt.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N

        jLabel8.setBackground(new java.awt.Color(247, 247, 255));
        jLabel8.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLabel8.setText("ZipCode:");

        jZip.setBackground(new java.awt.Color(247, 247, 255));
        jZip.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLPatPhone)
                            .addComponent(jLPatEmail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPatientPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPatientEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLPatName)
                            .addComponent(jLabel3)
                            .addComponent(jLPatDob)
                            .addComponent(jLPatAge)
                            .addComponent(jLPatGender))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jId, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTPatientAge, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(135, 135, 135)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox2, 0, 161, Short.MAX_VALUE)
                    .addComponent(jComboBox3, 0, 161, Short.MAX_VALUE)
                    .addComponent(jSt, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(jApt)
                    .addComponent(jZip))
                .addContainerGap(127, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addGap(41, 41, 41)
                        .addComponent(jButton4)
                        .addGap(67, 67, 67)
                        .addComponent(jButton5)
                        .addGap(180, 180, 180))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(341, 341, 341))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLPatName)
                            .addComponent(jPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLPatDob)
                                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(jApt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLPatAge)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTPatientAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6)
                                .addComponent(jSt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLPatGender)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(jZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLPatPhone)
                    .addComponent(jPatientPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLPatEmail)
                    .addComponent(jPatientEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton4)
                        .addComponent(jButton5))
                    .addComponent(jButton6))
                .addContainerGap(59, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jIdActionPerformed

    private void jPatientPhoneNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPatientPhoneNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPatientPhoneNoActionPerformed

    private void jPatientEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPatientEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPatientEmailActionPerformed

    private void jTPatientAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTPatientAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTPatientAgeActionPerformed

    private void jPatientNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPatientNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPatientNameActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        beforeEditcity = (String) jComboBox2.getSelectedItem();
        beforeEditComm = (String) jComboBox3.getSelectedItem();
        jId.setEnabled(true);
        jPatientName.setEnabled(true);
        jPatientEmail.setEnabled(true);
        jPatientPhoneNo.setEnabled(true);
        jDateChooser2.setEnabled(true);
        jComboBox1.setEnabled(true);
        jButton4.setVisible(false);
        jApt.setEnabled(true);
        jSt.setEnabled(true);
        jZip.setEnabled(true);
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
             String selectedCity = (String) jComboBox2.getSelectedItem();
        City selected  = new City();
        jComboBox3.removeAllItems();
        selected = cityLog.searchCity(selectedCity);
        for (int i =0;i<selected.getCommunityCatalog().size();i++){
            Community comm = new Community();
            comm = selected.getCommunityCatalog().get(i);
            jComboBox3.addItem(comm.getCommunityName());

        }
  
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
       String id =  jId.getText();
       String name = jPatientName.getText();
       String email =  jPatientEmail.getText();
       String phnNo = jPatientPhoneNo.getText();
       String city = (String) jComboBox2.getSelectedItem();
       String comm = (String) jComboBox3.getSelectedItem();
       String aptNo = jApt.getText();
       String StNo =  jSt.getText();
       String zip =  jZip.getText();
       Date dob = jDateChooser2.getDate();
       String gender = (String) jComboBox1.getSelectedItem();
       
        if(name.trim().length() == 0 ||id.trim().length() == 0|| gender.trim().length() == 0 || phnNo.trim().length() == 0|| email.trim().length() == 0 || aptNo.trim().length() == 0 ||jSt.getText().trim().length() == 0|| zip.trim().length() ==0){
            JOptionPane.showMessageDialog(this, "All Fields must be entered");
        }
//        if(firstName.trim().length()>0 && lastName.trim().length()>0){
//                People p1 = new People();
//                p1.setDob(dob);
//                p1.setEmail(email);
//                p1.setId(id);
//                p1.setName(name);
//                p1.setPhone(phnNo);
//                p1.setHouse(new House(aptNo,StNo,zip));
//                p1.setGender(gender);
//                City c= cityLog.searchCity(city);
//                c.getCommunityCatalog().searchCommunity(comm).getPeopleCatalog().addPeople(p);
//                City oldCity  = cityLog.searchCity(beforeEditcity);
//                oldCity.getCommunityCatalog().searchCommunity(beforeEditComm).getPeopleCatalog().removePeople(p);
//            }
            else{
                p.setDob(dob);
                p.setEmail(email);
                p.setId(id);
                p.setName(name);
                p.setPhone(phnNo);
                p.setHouse(new House(aptNo,StNo,zip));
                p.setGender(gender);
            }
            ReportPage rp = new ReportPage(jSplitPane2,p,comm1, cityLog,new City());
            jSplitPane2.setRightComponent(rp);
        
    }//GEN-LAST:event_jButton5ActionPerformed

    public void disableTextFields(){
        jPatientName.setEditable(false);
        jDateChooser2.setEnabled(false);
//        jPatientGender.setEditable(false);
//        jPatientAddress.setEditable(false);
        jPatientPhoneNo.setEditable(false);
        jPatientEmail.setEditable(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jApt;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JTextField jId;
    private javax.swing.JLabel jLPatAge;
    private javax.swing.JLabel jLPatDob;
    private javax.swing.JLabel jLPatEmail;
    private javax.swing.JLabel jLPatGender;
    private javax.swing.JLabel jLPatName;
    private javax.swing.JLabel jLPatPhone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jPatientEmail;
    private javax.swing.JTextField jPatientName;
    private javax.swing.JTextField jPatientPhoneNo;
    private javax.swing.JTextField jSt;
    private javax.swing.JTextField jTPatientAge;
    private javax.swing.JTextField jZip;
    // End of variables declaration//GEN-END:variables
}
