/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Hopsital;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSplitPane;
import ComEnterprise.City;
import ComEnterprise.CityCatalouge;
import ComEnterprise.Community;
import ComEnterprise.CommunityCatalouge;
import HospitalEnterprise.Hospital;
import UserInterface.Community.CommunityAdmin;

/**
 *
 * @author namithajc
 */
public class HospitalDetails extends javax.swing.JPanel {

    /**
     * Creates new form HospitalDetails
     */
    JSplitPane jSplitPane2;
    JSplitPane jSplitPane1;
    CityCatalouge cityLog;
    JPanel mainPanel;
    JPanel jPanel2;
    boolean isView;
    Hospital hos;
    String selectedComm;
    String selectedCity;
    public HospitalDetails(JSplitPane jSplitPane2, JSplitPane jSplitPane1, CityCatalouge cityLog, JPanel mainPanel, JPanel jPanel2, boolean isView, Hospital hos, String selectedComm, String selectedCity) {
        initComponents();
        this.jSplitPane1 = jSplitPane1;
        this.jSplitPane2 = jSplitPane2;
        this.cityLog = cityLog;
        this.mainPanel = mainPanel;
        this.jPanel2 = jPanel2;
        this.isView = isView;
        this.hos = hos;
        this.selectedComm =selectedComm;
        this.selectedCity = selectedCity;
         for (int i = 0; i< cityLog.size();i++){
            jCity.addItem(cityLog.get(i).getCityName());
        }
         if(!isView){
             jEdit.setVisible(false);
             jSave.setVisible(false);
         }
         if(isView){
             jCity.setSelectedItem(selectedCity);
             jCommunity.setSelectedItem(selectedComm);
             jSubmit.setVisible(false);
             jSave.setEnabled(false);
             jHospitalName.setEnabled(false);
             jEmail.setEnabled(false);
             jPhnNo.setEnabled(false);
             jHospitalName.setText(hos.getHospitalName());
             jEmail.setText(hos.getEmailId());
             jPhnNo.setText(hos.getPhoneNo());
             jCity.setEnabled(false);
             jCommunity.setEnabled(false);
             
         }
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCity = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jCommunity = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jHospitalName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPhnNo = new javax.swing.JTextField();
        jSubmit = new javax.swing.JButton();
        jEdit = new javax.swing.JButton();
        jSave = new javax.swing.JButton();

        setBackground(new java.awt.Color(170, 185, 207));

        jLabel1.setFont(new java.awt.Font("Lava Kannada", 1, 14)); // NOI18N
        jLabel1.setText("Hospital Details");

        jLabel2.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLabel2.setText("City:");

        jCity.setBackground(new java.awt.Color(247, 247, 255));
        jCity.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCityActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(247, 247, 255));
        jLabel3.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLabel3.setText("Community:");

        jCommunity.setBackground(new java.awt.Color(247, 247, 255));
        jCommunity.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLabel4.setText("Hospital Name:");

        jHospitalName.setBackground(new java.awt.Color(247, 247, 255));
        jHospitalName.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N

        jLabel5.setBackground(new java.awt.Color(247, 247, 255));
        jLabel5.setFont(new java.awt.Font("Lava Kannada", 1, 14)); // NOI18N
        jLabel5.setText("Contact Details:");

        jLabel6.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLabel6.setText("Email:");

        jEmail.setBackground(new java.awt.Color(247, 247, 255));
        jEmail.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N

        jLabel7.setBackground(new java.awt.Color(247, 247, 255));
        jLabel7.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLabel7.setText("PhoneNo:");

        jPhnNo.setBackground(new java.awt.Color(247, 247, 255));
        jPhnNo.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N

        jSubmit.setBackground(new java.awt.Color(247, 247, 255));
        jSubmit.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jSubmit.setText("Submit");
        jSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubmitActionPerformed(evt);
            }
        });

        jEdit.setBackground(new java.awt.Color(247, 247, 255));
        jEdit.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jEdit.setText("Edit");
        jEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEditActionPerformed(evt);
            }
        });

        jSave.setBackground(new java.awt.Color(247, 247, 255));
        jSave.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jSave.setText("Save");
        jSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jHospitalName, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jCity, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jPhnNo, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSubmit)
                        .addGap(84, 84, 84)
                        .addComponent(jSave))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jEdit)
                        .addGap(351, 351, 351)))
                .addGap(86, 86, 86))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(246, 246, 246))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jHospitalName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jPhnNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jEdit)
                    .addComponent(jSubmit)
                    .addComponent(jSave))
                .addGap(67, 67, 67))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCityActionPerformed
        // TODO add your handling code here:
        String selectedCity = (String) jCity.getSelectedItem();
        City selected  = new City();
        jCommunity.removeAllItems();
        selected = cityLog.searchCity(selectedCity);
        CommunityCatalouge commLog = new CommunityCatalouge();
        commLog = selected.getCommunityCatalog();
         for(int i = 0 ; i < commLog.getCommunityCatalog().size();i++){
             jCommunity.addItem(commLog.get(i).getCommunityName());
         }  
    }//GEN-LAST:event_jCityActionPerformed

    private void jSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubmitActionPerformed
        // TODO add your handling code here:
        String name = jHospitalName.getText();
        String email = jEmail.getText();
        String phoneNo = jPhnNo.getText();
        if(name.trim().length() == 0 || email.trim().length() == 0|| phoneNo.trim().length() == 0){
         JOptionPane.showMessageDialog(this, "All Fields are mandatory");
        }
        else {
            String selectedCity = (String) jCity.getSelectedItem();
            String communityName = (String) jCommunity.getSelectedItem();
        City selected  = new City();
        selected = cityLog.searchCity(selectedCity);
        Community commLog = new Community();
        commLog = selected.getCommunityCatalog().searchCommunity(communityName);
        hos.setHospitalName(name);
        hos.setEmailId(email);
        hos.setPhoneNo(phoneNo);
        commLog.getHospitalCataloug().addHospital(hos);
        CommunityAdmin commAdmin = new CommunityAdmin(cityLog,jSplitPane2, commLog, mainPanel,selected,true);
        jSplitPane2.setRightComponent(commAdmin);
        
        }
    }//GEN-LAST:event_jSubmitActionPerformed

    private void jEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEditActionPerformed
        // TODO add your handling code here:
            jSave.setEnabled(true);
             jHospitalName.setEnabled(true);
             jEmail.setEnabled(true);
             jPhnNo.setEnabled(true);
             jEdit.setEnabled(false);
             jCity.setEnabled(true);
             jCommunity.setEnabled(true);
    }//GEN-LAST:event_jEditActionPerformed

    private void jSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveActionPerformed
        // TODO add your handling code here:
        String name = jHospitalName.getText();
        String email = jEmail.getText();
        String phoneNo = jPhnNo.getText();
        if(name.trim().length() == 0 || email.trim().length() == 0|| phoneNo.trim().length() == 0){
         JOptionPane.showMessageDialog(this, "All Fields are mandatory");
        }
        else {
            String selectedCity = (String) jCity.getSelectedItem();
            String communityName = (String) jCommunity.getSelectedItem();
        City selected  = new City();
        selected = cityLog.searchCity(selectedCity);
        Community commLog = new Community();
        commLog = selected.getCommunityCatalog().searchCommunity(communityName);
        hos.setHospitalName(name);
        hos.setEmailId(email);
        hos.setPhoneNo(phoneNo);
        CommunityAdmin commAdmin = new CommunityAdmin(cityLog,jSplitPane2, commLog, mainPanel,selected,true);
        jSplitPane2.setRightComponent(commAdmin);
        }
    }//GEN-LAST:event_jSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jCity;
    private javax.swing.JComboBox<String> jCommunity;
    private javax.swing.JButton jEdit;
    private javax.swing.JTextField jEmail;
    private javax.swing.JTextField jHospitalName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jPhnNo;
    private javax.swing.JButton jSave;
    private javax.swing.JButton jSubmit;
    // End of variables declaration//GEN-END:variables
}
