/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Hopsital;

import Business.Organization;
import CommunityEnterprise.City;
import CommunityEnterprise.CityDirectory;
import CommunityEnterprise.Community;
import CommunityEnterprise.CommunityDirectory;
import CommunityEnterprise.People;
import CommunityEnterprise.PeopleDirectory;
import HospitalEnterprise.Hospital;
import HospitalEnterprise.HospitalDirectory;
import java.util.Date;
import static java.util.Objects.isNull;
import javax.swing.JOptionPane;
import javax.swing.JSplitPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author namithajc
 */
public class ManageHospitalsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageHospitalsJPanel
     */
    JSplitPane jSplitPane2;
    
    boolean isPresent = false;
    Organization system;
    People selectedPerson;
    boolean isEdit = false;
    String beforeEdit;
        public ManageHospitalsJPanel(Organization system) {
        initComponents();
        this.system = system;
        populateTable();
        jButton2.setVisible(false);
        jButton3.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jhospital1 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jCommunity = new javax.swing.JComboBox<>();
        jCity = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jhospital2 = new javax.swing.JTextField();
        jhospital3 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setBackground(new java.awt.Color(237, 231, 217));

        jTabbedPane1.setBackground(new java.awt.Color(237, 231, 217));

        jPanel3.setBackground(new java.awt.Color(237, 231, 217));

        jLabel3.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLabel3.setText("Hospital Name:");

        jLabel4.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLabel4.setText("Community:");

        jLabel5.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLabel5.setText("City:");

        jLabel6.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLabel6.setText("ZipCode:");

        jButton1.setBackground(new java.awt.Color(247, 247, 255));
        jButton1.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(247, 247, 255));
        jButton2.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(247, 247, 255));
        jButton3.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jButton3.setText("Save");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jhospital1.setBackground(new java.awt.Color(247, 247, 255));
        jhospital1.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N

        jTextField4.setBackground(new java.awt.Color(247, 247, 255));
        jTextField4.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N

        jCommunity.setBackground(new java.awt.Color(247, 247, 255));
        jCommunity.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jCommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCommunityActionPerformed(evt);
            }
        });

        jCity.setBackground(new java.awt.Color(247, 247, 255));
        jCity.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCityActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLabel2.setText("Email:");

        jLabel7.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLabel7.setText("Phone number:");

        jhospital2.setBackground(new java.awt.Color(247, 247, 255));
        jhospital2.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N

        jhospital3.setBackground(new java.awt.Color(247, 247, 255));
        jhospital3.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jCity, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                .addComponent(jhospital3)
                                .addComponent(jhospital2)
                                .addComponent(jhospital1))
                            .addComponent(jCommunity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(120, 120, 120))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jhospital1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jhospital2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jhospital3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(57, 57, 57)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add and Edit Hospitals", jPanel3);

        jPanel4.setBackground(new java.awt.Color(237, 231, 217));

        jTable1.setBackground(new java.awt.Color(237, 231, 217));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Hospital Name", "Community", "City", "ZipCode"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton4.setText("Delete");

        jButton5.setText("Delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("View");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(164, 164, 164))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(77, 77, 77))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addGap(23, 23, 23)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("View and Delete Hospitals", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(141, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String name = jhospital1.getText();
        String email = jhospital2.getText();
        String phone = jhospital2.getText();
//        String com = (String) jCommunity.getSelectedItem();
//        String city = (String)jCity.getSelectedItem();
        String selectedCity = (String) jCity.getSelectedItem();
        String communityName = (String) jCommunity.getSelectedItem();
        City selected  = new City();
        selected = system.getCityDirectory().getCityByName(selectedCity);
       //int zipCode = jTextField4.getText();
       Community selComm = selected.getComDir().getCommunityByName(communityName);
       String zipCode = jTextField4.getText();
        
        isPresent = selComm.getHospDirectory().checkHospital(name);
        if(isPresent){
            JOptionPane.showMessageDialog(this, "Hospital is present");
        }
        else{
            if(name.trim().length()>0 && email.trim().length()>0 && phone.trim().length()>0 && zipCode.trim().length()>0){
            Hospital h = new Hospital();
            h.setName(name);
            h.setEmail(email);
            h.setPhone(phone);
            h.setZipCode(zipCode);
//            Email.sendMail("New User Created","Mm","aa","manju.pratuv@gmail.com");
            String selCity = (String) jCity.getSelectedItem();
            City c = system.getCityDirectory().getCityByName(selCity);
            String comm = (String) jCommunity.getSelectedItem();
            Community c1 = c.getComDir().getCommunityByName(comm);
            c1.getHospDirectory().addHospital(h);
             JOptionPane.showMessageDialog(this, "New Hospital Created"); 
             jhospital1.setText("");
             jhospital2.setText("");
            jhospital2.setText("");
            jhospital3.setText("");
            jTextField4.setText("");
            populateTable();
            }
            else{
                JOptionPane.showMessageDialog(this, "Fill all the fields"); 
            }
            
            
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
                    jhospital1.setEditable(true);
                    jhospital2.setEditable(true);
                    jhospital3.setEditable(true);
                    jTextField4.setEditable(true);
                    jCity.setEnabled(true);
                    jCommunity.setEnabled(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String name = jhospital1.getText();
        String email = jhospital2.getText();
        String phone = jhospital3.getText();
//        String com = (String) jCommunity.getSelectedItem();
//        String city = (String)jCity.getSelectedItem();
        String selectedCity = (String) jCity.getSelectedItem();
        String communityName = (String) jCommunity.getSelectedItem();
        City selected  = new City();
        selected = system.getCityDirectory().getCityByName(selectedCity);
       //int zipCode = jTextField4.getText();
       Community selComm = selected.getComDir().getCommunityByName(communityName);
      
       String zipCode = jTextField4.getText();
            if(name.trim().length()>0 && email.trim().length()>0 && phone.trim().length()>0 && zipCode.trim().length()>0){
            Hospital h = selComm.getHospDirectory().getHospitalByName(beforeEdit);
            h.setName(name);
            h.setEmail(email);
            h.setPhone(phone);
            h.setZipCode(zipCode);
//            Email.sendMail("New User Created","Mm","aa","manju.pratuv@gmail.com");
            String selCity = (String) jCity.getSelectedItem();
            City c = system.getCityDirectory().getCityByName(selCity);
            String comm = (String) jCommunity.getSelectedItem();
            Community c1 = c.getComDir().getCommunityByName(comm);
             JOptionPane.showMessageDialog(this, "Hospital Updated"); 
             jhospital1.setText("");
             jhospital2.setText("");
            jhospital2.setText("");
            jhospital3.setText("");
            jTextField4.setText("");
            populateTable();
            }
            else{
                JOptionPane.showMessageDialog(this, "Fill all the fields"); 
            }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCityActionPerformed
        // TODO add your handling code here:
        jCommunity.removeAllItems();
        String selectedCity = (String) jCity.getSelectedItem();
        City selected = system.getCityDirectory().getCityByName(selectedCity);
        CommunityDirectory commLog = selected.getComDir();
         for(int i = 0 ; i < commLog.getCommunityList().size();i++){
             jCommunity.addItem(commLog.getCommunityList().get(i).getName());
         }
    }//GEN-LAST:event_jCityActionPerformed

    
    private void jCommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCommunityActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jCommunityActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int selectedRow = jTable1.getSelectedRow();
        if(selectedRow == -1){
            JOptionPane.showMessageDialog(this, "Please Select a Row");
        }
        else{
            jTabbedPane1.setSelectedIndex(0);
            String selectedHosp = (String) model.getValueAt(selectedRow,0);
            String selectedCommunity = (String) model.getValueAt(selectedRow,1);
            String selectedCity = (String) model.getValueAt(selectedRow,2);
            System.out.println(selectedCity);
            City c = system.getCityDirectory().getCityByName(selectedCity);
            Community c1 = c.getComDir().getCommunityByName(selectedCommunity);
             for(int i =0; i<c1.getHospDirectory().gethospList().size();i++){
                    if(selectedHosp.equalsIgnoreCase(c1.getHospDirectory().gethospList().get(i).getName())){
                        Hospital h = c1.getHospDirectory().gethospList().get(i);
                    beforeEdit  = selectedHosp;
                    jhospital1.setText(h.getName());
                    jhospital2.setText(h.getEmail());
                    jhospital3.setText(h.getPhone());
                    jTextField4.setText(h.getZipCode());
                    jCity.setSelectedItem(selectedCity);
                    jCommunity.setSelectedItem(selectedCommunity); 
                    jButton1.setVisible(false);
                    jButton2.setVisible(true);
                    jButton3.setVisible(true);
                    jhospital1.setEditable(false);
                    jhospital2.setEditable(false);
                    jhospital3.setEditable(false);
                    jTextField4.setEditable(false);
                    jCity.setEnabled(false);
                    jCommunity.setEnabled(false); 
                    }
              }
        }
      
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int selectedRow = jTable1.getSelectedRow();
        if(selectedRow == -1){
            JOptionPane.showMessageDialog(this, "Please Select a Row");
        }
        else{
            jTabbedPane1.setSelectedIndex(0);
            String selectedHosp = (String) model.getValueAt(selectedRow,0);
            String selectedCommunity = (String) model.getValueAt(selectedRow,1);
            String selectedCity = (String) model.getValueAt(selectedRow,2);
            System.out.println(selectedCity);
            City c = system.getCityDirectory().getCityByName(selectedCity);
            Community c1 = c.getComDir().getCommunityByName(selectedCommunity);
            Hospital h = c1.getHospDirectory().getHospitalByName(selectedHosp);
            c1.getHospDirectory().removeHospital(h);
            populateTable();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    public void populateTable(){
        for (int i = 0; i< system.getCityDirectory().getCityList().size();i++){
            jCity.addItem(system.getCityDirectory().getCityList().get(i).getCityName());
        }
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
         model.setRowCount(0);
        
         for (int i =0;i<system.getCityDirectory().getCityList().size();i++){
             City c = system.getCityDirectory().getCityList().get(i);
             for (int j=0;j<c.getComDir().getCommunityList().size();j++ ){
                Community c1 = c.getComDir().getCommunityList().get(j);
                System.out.println(c1);
                 for (int k=0; k<c1.getHospDirectory().gethospList().size();k++){
                     Object rowData[] = new Object[4];
                        rowData[0] = c1.getHospDirectory().gethospList().get(k).getName();
                        rowData[1] = c1.getName();
                        rowData[2] = c.getCityName();
                        rowData[3] = c1.getHospDirectory().gethospList().get(k).getZipCode();
                        model.addRow(rowData);
                 }         
        }
    }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jCity;
    private javax.swing.JComboBox<String> jCommunity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jhospital1;
    private javax.swing.JTextField jhospital2;
    private javax.swing.JTextField jhospital3;
    // End of variables declaration//GEN-END:variables
}
