/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Hopsital;

import Business.Organization;
import CommunityEnterprise.City;
import CommunityEnterprise.CityDirectory;
import CommunityEnterprise.Community;
import CommunityEnterprise.CommunityDirectory;
import CommunityEnterprise.LoginCredentials;
import CommunityEnterprise.People;
import CommunityEnterprise.PeopleDirectory;
import HospitalEnterprise.DoctorDirectory;
import HospitalEnterprise.Hospital;
import HospitalEnterprise.HospitalDirectory;
import HospitalEnterprise.Patient;
import HospitalEnterprise.PatientDirectory;
import java.time.Instant;
import java.time.LocalDate;
import java.time.Period;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JSplitPane;

/**
 *
 * @author namithajc
 */
public class PatientRegistrationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientJPanel
     */
    Organization system;
    JSplitPane jSplitPane1;
    CityDirectory cityList;
    DoctorDirectory doctor;
    CommunityDirectory com;
    PeopleDirectory people;
    boolean isPresent = false;
    boolean isView;
    //PatientDirectory patient;
    
    public PatientRegistrationJPanel(Organization system,JSplitPane jSplitPane1,boolean isView) {
        initComponents();
        this.isView = isView;
        this.system = system;
        this.cityList = cityList;
        this.jSplitPane1 = jSplitPane1;
        for (int i = 0; i< system.getCityDirectory().getCityList().size();i++){
            jcity.addItem(system.getCityDirectory().getCityList().get(i).getCityName());
        }
        
        
//    if(!isView){
//             //jButton4.setVisible(false);
//         }
//         if(isView){
//             jPatientName.setEnabled(false);
//             jTextField1.setEnabled(false);
//             jAptNo.setEnabled(false);
//             jstNo.setEnabled(false);
//             jCommunity.setEnabled(false);
//             jcity.setEnabled(false);
//             jHospital.setEnabled(false);
//             jDateChooser1.setEnabled(false);
//                //jTPatientAge.setAge(p.)
//             jComboBox1.setEnabled(false);
//             jPatientEmail.setEnabled(false);
//             jPatientPhoneNo.setEnabled(false);
//             jSt.setEnabled(false);
//         }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLPatGender = new javax.swing.JLabel();
        jLPatPhone = new javax.swing.JLabel();
        jPatientName = new javax.swing.JTextField();
        jTPatientAge = new javax.swing.JTextField();
        jPatientEmail = new javax.swing.JTextField();
        jLPatEmail = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jId = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jstNo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jSt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPatientPhoneNo = new javax.swing.JTextField();
        jLPatName = new javax.swing.JLabel();
        jLPatDob = new javax.swing.JLabel();
        jLPatAge = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jcity = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jCommunity = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jAptNo = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jHospital = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPassword = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Lifesavers - PatientStanding.png"))); // NOI18N

        jLPatGender.setBackground(new java.awt.Color(247, 247, 255));
        jLPatGender.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLPatGender.setText("Gender:");

        jLPatPhone.setBackground(new java.awt.Color(247, 247, 255));
        jLPatPhone.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLPatPhone.setText("Phone:");

        jPatientName.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jPatientName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPatientNameActionPerformed(evt);
            }
        });

        jTPatientAge.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jTPatientAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTPatientAgeActionPerformed(evt);
            }
        });

        jPatientEmail.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jPatientEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPatientEmailActionPerformed(evt);
            }
        });
        jPatientEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPatientEmailKeyReleased(evt);
            }
        });

        jLPatEmail.setBackground(new java.awt.Color(247, 247, 255));
        jLPatEmail.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLPatEmail.setText("Email:");

        jLabel3.setBackground(new java.awt.Color(247, 247, 255));
        jLabel3.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLabel3.setText("SSN:");

        jId.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIdActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(247, 247, 255));
        jLabel8.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLabel8.setText("Address Line2:");

        jstNo.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N

        jLabel9.setBackground(new java.awt.Color(247, 247, 255));
        jLabel9.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLabel9.setText("ZipCode:");

        jSt.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N

        jLabel11.setBackground(new java.awt.Color(247, 247, 255));
        jLabel11.setForeground(new java.awt.Color(255, 51, 51));

        jLabel12.setBackground(new java.awt.Color(247, 247, 255));
        jLabel12.setForeground(new java.awt.Color(255, 51, 51));

        jPatientPhoneNo.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jPatientPhoneNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPatientPhoneNoActionPerformed(evt);
            }
        });
        jPatientPhoneNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPatientPhoneNoKeyReleased(evt);
            }
        });

        jLPatName.setBackground(new java.awt.Color(247, 247, 255));
        jLPatName.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLPatName.setText("First Name:");

        jLPatDob.setBackground(new java.awt.Color(247, 247, 255));
        jLPatDob.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLPatDob.setText("Date Of Birth:");

        jLPatAge.setBackground(new java.awt.Color(247, 247, 255));
        jLPatAge.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLPatAge.setText("Age:");

        jButton4.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jButton4.setText("Register");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jcity.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jcity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcityActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(247, 247, 255));
        jLabel5.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLabel5.setText("City:");

        jLabel6.setBackground(new java.awt.Color(247, 247, 255));
        jLabel6.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLabel6.setText("Community:");

        jCommunity.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jCommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCommunityActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(247, 247, 255));
        jLabel7.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLabel7.setText("Adress Line1:");

        jAptNo.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N

        jDateChooser1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jDateChooser1InputMethodTextChanged(evt);
            }
        });
        jDateChooser1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooser1PropertyChange(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLabel1.setText("Hospital:");

        jLabel4.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLabel4.setText("or");

        jLabel13.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLabel13.setText("Create Password:");

        jPassword.setSize(new java.awt.Dimension(78, 32));
        jPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLabel14.setText("Last Name:");

        jTextField1.setText("jTextField1");

        jButton2.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jButton2.setText("Register Manually");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Others" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(64, 64, 64)
                                                .addComponent(jLPatName))
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel3)
                                                    .addComponent(jLabel14)
                                                    .addComponent(jLPatDob)
                                                    .addComponent(jLPatAge)
                                                    .addComponent(jLPatGender))))
                                        .addGap(6, 6, 6))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLPatEmail)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPatientName)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTPatientAge)
                                    .addComponent(jPatientEmail)
                                    .addComponent(jId)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLPatPhone))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPatientPhoneNo)
                                    .addComponent(jPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(132, 132, 132)
                                        .addComponent(jLabel5)
                                        .addGap(6, 6, 6)
                                        .addComponent(jcity, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(84, 84, 84)
                                        .addComponent(jLabel6)
                                        .addGap(6, 6, 6)
                                        .addComponent(jCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(104, 104, 104)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel7))
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jAptNo)
                                            .addComponent(jHospital, 0, 161, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(80, 80, 80)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jstNo, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(104, 104, 104)
                                        .addComponent(jLabel9)
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(58, 58, 58)
                                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jSt, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton2)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(299, 299, 299)
                        .addComponent(jButton4)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel4)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLPatName)
                    .addComponent(jPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel5))
                            .addComponent(jcity, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel6))
                            .addComponent(jCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel7))
                            .addComponent(jAptNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jstNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(62, 62, 62)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLPatDob)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTPatientAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addComponent(jHospital, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLPatAge))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLPatGender)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jPatientEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLPatEmail))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLPatPhone))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jPatientPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(248, 248, 248))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jPatientNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPatientNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPatientNameActionPerformed

    private void jTPatientAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTPatientAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTPatientAgeActionPerformed

    private void jPatientEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPatientEmailActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jPatientEmailActionPerformed

    private void jPatientEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPatientEmailKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_jPatientEmailKeyReleased

    private void jIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jIdActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
//        jPatientName.setEnabled(true);
//        jTextField1.setEnabled(true);
//        jAptNo.setEnabled(true);
//        jstNo.setEnabled(true);
//        jCommunity.setEnabled(true);
//        jcity.setEnabled(true);
//        jHospital.setEnabled(true);
//        jDateChooser1.setEnabled(true);
//                //jTPatientAge.setAge(p.)
//        jComboBox1.setEnabled(true);
//        jPatientEmail.setEnabled(true);
//        jPatientPhoneNo.setEnabled(true);
//        jSt.setEnabled(true);
             
        String ssn = jId.getText();
        if(ssn.trim().length()>0){
            Patient p = system.getPatientDirectory().findPatientBySSn(ssn);
            if(p == null){
                JOptionPane.showMessageDialog(this, "User Not Found");
            }
            else {
                isPresent = true;
                jPatientName.setText(p.getFirstName());
                jTextField1.setText(p.getLastName());
                jAptNo.setText(p.getAddressLine1());
                jstNo.setText(p.getAddressLine2());
                jCommunity.setSelectedItem(p.getCommunity());
                jcity.setSelectedItem(p.getCity());
                jHospital.setSelectedItem(p.getHospital());
                jDateChooser1.setDate(p.getDob());
                //jTPatientAge.setAge(p.)
                jComboBox1.setSelectedItem(p.getGender());
                jPatientEmail.setText(p.getSsn());
                jPatientPhoneNo.setText(p.getPhoneNo());
                jSt.setText(p.getZipCode());
                //jPatientPhoneNo.setText(p.getPhoneNo());
                
            }
        }
        else {
            JOptionPane.showMessageDialog(this, "Please Enter the SSN");

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPatientPhoneNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPatientPhoneNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPatientPhoneNoActionPerformed

    private void jPatientPhoneNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPatientPhoneNoKeyReleased
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jPatientPhoneNoKeyReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String id = jId.getText();
        String selectedCity = (String) jcity.getSelectedItem();
        String selectedComm = (String) jCommunity.getSelectedItem();
        String selectedHosp = (String) jHospital.getSelectedItem();
        City city = system.getCityDirectory().getCityByName(selectedCity);
        Community com = city.getComDir().getCommunityByName(selectedComm);
        Hospital hosp = com.getHospDirectory().getHospitalByName(selectedHosp);
        
        Patient patient = new Patient();
        String fname = jPatientName.getText();
        String lname = jPatientName.getText();
        Date dob = jDateChooser1.getDate();
        String gender = (String) jComboBox1.getSelectedItem();
        String phoneNo = jPatientPhoneNo.getText();
        String email = jPatientEmail.getText();
        String password = jPassword.getText();
        String aptNo = jAptNo.getText();
        String stNo = jstNo.getText();
        String zip = jSt.getText();
        LoginCredentials temp = new LoginCredentials();
        temp.setEmail(email);
        temp.setPassword(password);
        //String username = ssn
        //temp.setUserName(lname);
        
        patient.setSsn(id);
        patient.setFirstName(fname);
        patient.setLastName(lname);
        patient.setPhoneNo(phoneNo);
        patient.setAddressLine1(aptNo);
        patient.setAddressLine2(stNo);
        patient.setCity(city.getCityName());
        patient.setCommunity(com.getName());
        patient.setDob(dob);
        patient.setEmailId(email);
        patient.setGender(gender);
        patient.setLoginCredentials(patient);
        patient.setPassword(password);
        patient.setZipCode(zip);
        patient.setLoginCredentials(new LoginCredentials(fname+id,password,email));
     
        if(fname.trim().length() == 0 || lname.trim().length() == 0 || id.trim().length() == 0|| gender.trim().length() == 0 || phoneNo.trim().length() == 0|| email.trim().length() == 0 ){
            JOptionPane.showMessageDialog(this, "All Fields must be entered");
        }
        else{
//            hosp.getPatientCatalouge().addPatient(people);
            PatloginJPanel patLog = new PatloginJPanel(system);
            jSplitPane1.setRightComponent(patLog);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jcityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcityActionPerformed
        // TODO add your handling code here:
        
        jCommunity.removeAllItems();
        String selectedCity = (String) jcity.getSelectedItem();
        City selected = system.getCityDirectory().getCityByName(selectedCity);
        CommunityDirectory commLog = selected.getComDir();
         for(int i = 0 ; i < commLog.getCommunityList().size();i++){
             jCommunity.addItem(commLog.getCommunityList().get(i).getName());
         }

    }//GEN-LAST:event_jcityActionPerformed

    private void jCommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCommunityActionPerformed
        // TODO add your handling code here:
        //jHospital.removeAllItems();
        String selectedCity = (String) jcity.getSelectedItem();
        City citySelected = system.getCityDirectory().getCityByName(selectedCity);
        String selectedCom = (String) jCommunity.getSelectedItem();
        Community comSelected = citySelected.getComDir().getCommunityByName(selectedCom);
        HospitalDirectory hosp = comSelected.getHospDirectory();
         for(int i = 0 ; i < hosp.gethospList().size();i++){
             jHospital.addItem(hosp.gethospList().get(i).getName());
         }
    }//GEN-LAST:event_jCommunityActionPerformed

    private void jPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordActionPerformed

    private void jDateChooser1InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jDateChooser1InputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jDateChooser1InputMethodTextChanged

    private void jDateChooser1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooser1PropertyChange
        // TODO add your handling code here:
        LocalDate curDate = LocalDate.now();
        if(jDateChooser1.getDate()!=null){
            Instant instant = jDateChooser1.getDate().toInstant();
        ZonedDateTime zone = instant.atZone(ZoneId.systemDefault());
        LocalDate givenDate = zone.toLocalDate();
        int age1  = Period.between(givenDate,curDate).getYears();
        String age = String.valueOf(age1);
        jTPatientAge.setText(age);
        jTPatientAge.setEditable(false);
        }
    }//GEN-LAST:event_jDateChooser1PropertyChange

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jPatientName.setEnabled(true);
        jTextField1.setEnabled(true);
        jAptNo.setEnabled(true);
        jstNo.setEnabled(true);
        jCommunity.setEnabled(true);
        jcity.setEnabled(true);
        jHospital.setEnabled(true);
        jDateChooser1.setEnabled(true);
                //jTPatientAge.setAge(p.)
        jComboBox1.setEnabled(true);
        jPatientEmail.setEnabled(true);
        jPatientPhoneNo.setEnabled(true);
        jSt.setEnabled(true);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jAptNo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jCommunity;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JComboBox<String> jHospital;
    private javax.swing.JTextField jId;
    private javax.swing.JLabel jLPatAge;
    private javax.swing.JLabel jLPatDob;
    private javax.swing.JLabel jLPatEmail;
    private javax.swing.JLabel jLPatGender;
    private javax.swing.JLabel jLPatName;
    private javax.swing.JLabel jLPatPhone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jPassword;
    private javax.swing.JTextField jPatientEmail;
    private javax.swing.JTextField jPatientName;
    private javax.swing.JTextField jPatientPhoneNo;
    private javax.swing.JTextField jSt;
    private javax.swing.JTextField jTPatientAge;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox<String> jcity;
    private javax.swing.JTextField jstNo;
    // End of variables declaration//GEN-END:variables
}
