/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Hopsital;

import static Business.Organization.system;
import static java.lang.String.valueOf;
import java.time.Instant;
import java.time.LocalDate;
import java.time.Period;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import javax.swing.JSplitPane;
import javax.swing.table.DefaultTableModel;
import ComEnterprise.City;
import ComEnterprise.CityCatalouge;
import ComEnterprise.Community;
import ComEnterprise.People;
import UserInterface.Patient.ViewInsurancePlansJPanel;

/**
 *
 * @author namithajc
 */
public class ReportPage extends javax.swing.JPanel {

    /**
     * Creates new form ReportPage
     */
    JSplitPane jSplitPane2;
    People p;
    Community comm;
    CityCatalouge cityLog;
    City c;
    public ReportPage(JSplitPane jSplitPane2, People p, Community comm, CityCatalouge cityLog, City city) {
        initComponents();
        this.p = p;
        this.c = city;
        this.comm = comm;
        this.jSplitPane2 = jSplitPane2;
        this.cityLog = cityLog;
        jIdLabel.setText(p.getId());
        LocalDate curDate = LocalDate.now();
        Instant instant = p.getDob().toInstant();
        ZonedDateTime zone = instant.atZone(ZoneId.systemDefault());
        LocalDate givenDate = zone.toLocalDate();
        int age  = Period.between(givenDate,curDate).getYears();
        jAgeLabel.setText(valueOf(age));
        jNamePlaceholder.setText(p.getName());
        jGenderLabel.setText(p.getGender());
        jContactLabel.setText(p.getPhone());
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jIdLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jNamePlaceholder = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jAgeLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jGenderLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jContactLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        jTable1.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Date", "BP", "Heart Rate", "Temperature", "Weight", "Height", "Respiratory Rate"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setBackground(new java.awt.Color(170, 185, 207));

        jLabel1.setFont(new java.awt.Font("Lava Kannada", 1, 14)); // NOI18N
        jLabel1.setText("Patient Details");

        jLabel3.setFont(new java.awt.Font("Lava Kannada", 1, 14)); // NOI18N
        jLabel3.setText("ID:");

        jIdLabel.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jIdLabel.setText("ID placeholder");

        jLabel4.setFont(new java.awt.Font("Lava Kannada", 1, 14)); // NOI18N
        jLabel4.setText("Name:");

        jNamePlaceholder.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jNamePlaceholder.setText("Name placeholder");

        jLabel6.setFont(new java.awt.Font("Lava Kannada", 1, 14)); // NOI18N
        jLabel6.setText("Age:");

        jAgeLabel.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jAgeLabel.setText("Age:");

        jLabel8.setFont(new java.awt.Font("Lava Kannada", 1, 14)); // NOI18N
        jLabel8.setText("Gender:");

        jGenderLabel.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jGenderLabel.setText("Age:");

        jLabel10.setFont(new java.awt.Font("Lava Kannada", 1, 14)); // NOI18N
        jLabel10.setText("Contact number:");

        jContactLabel.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jContactLabel.setText("Contact number:");

        jScrollPane2.setBackground(new java.awt.Color(247, 247, 255));

        jTable2.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Doctor Name", "BP", "Heart Rate", "Temperature", "Weight", "Height", "Respiratory Rate"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButton2.setBackground(new java.awt.Color(247, 247, 255));
        jButton2.setFont(new java.awt.Font("Lava Kannada", 0, 12)); // NOI18N
        jButton2.setText("Edit Details");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(247, 247, 255));
        jButton3.setFont(new java.awt.Font("Lava Kannada", 0, 12)); // NOI18N
        jButton3.setText("Schedule Appointment");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton9.setText("View Insurance Plans");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jIdLabel)
                            .addComponent(jNamePlaceholder)
                            .addComponent(jGenderLabel)
                            .addComponent(jAgeLabel)
                            .addComponent(jContactLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(22, 22, 22)))
                .addGap(108, 108, 108)
                .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addGap(298, 298, 298)
                .addComponent(jButton3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton2))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jIdLabel))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jNamePlaceholder))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jGenderLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jAgeLabel)
                    .addComponent(jButton9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jContactLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(39, 39, 39))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        EditPatientDetails editDetails = new EditPatientDetails(jSplitPane2,p,comm,cityLog);
        jSplitPane2.setRightComponent(editDetails);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        ScheduleAppointment schApp = new ScheduleAppointment(jSplitPane2,cityLog,p, comm,c);
        jSplitPane2.setRightComponent(schApp);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        ViewInsurancePlansJPanel viewplans = new ViewInsurancePlansJPanel(system,jSplitPane2);
        jSplitPane2.setRightComponent(viewplans);

    }//GEN-LAST:event_jButton9ActionPerformed

    void populateTable(){
       DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
       model.setRowCount(0);
       for(int i = 0 ;i < p.getEncounterHistory().size();i++){
           System.out.println(p.getEncounterHistory().get(i));
           Object rowData[] = new Object[8];
           rowData[0] = p.getEncounterHistory().get(i).getEncounterDate();
           rowData[1] = p.getEncounterHistory().get(i).getDoctorName();
           rowData[2] = p.getEncounterHistory().get(i).getVitalsigns().getBloodpressure();
           rowData[3] = p.getEncounterHistory().get(i).getVitalsigns().getHeartRate();
           rowData[4] = p.getEncounterHistory().get(i).getVitalsigns().getTemperature();
           rowData[5] = p.getEncounterHistory().get(i).getVitalsigns().getWeight();
           rowData[6] = p.getEncounterHistory().get(i).getVitalsigns().getHeight();
           rowData[7] = p.getEncounterHistory().get(i).getVitalsigns().getRespiratoryRate();
           model.addRow(rowData);
       }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAgeLabel;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jContactLabel;
    private javax.swing.JLabel jGenderLabel;
    private javax.swing.JLabel jIdLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jNamePlaceholder;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
