/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Hopsital;

import java.util.Date;
import javax.swing.JSplitPane;
import HospitalEnterprise.Appointments;
import ComEnterprise.City;
import ComEnterprise.CityCatalouge;
import ComEnterprise.Community;
import HospitalEnterprise.Hospital;
import HospitalEnterprise.HospitalCatalouge;
import ComEnterprise.People;

/**
 *
 * @author namithajc
 */
public class ScheduleAppointment extends javax.swing.JPanel {

    /**
     * Creates new form ScheduleAppointment
     */
    JSplitPane jSplitPane2;
    CityCatalouge cityLog;
    People p;
    Community comm;
    City c;
    public ScheduleAppointment(JSplitPane jSplitPane2, CityCatalouge cityLog, People p, Community comm, City c) {
        initComponents();
        this.c = c;
        this.jSplitPane2 = jSplitPane2;
        this.cityLog = cityLog;
        this.p = p;
        this.comm = comm;
        jDateChooser1.getJCalendar().setMinSelectableDate(new Date());
        for(int j = 0; j< cityLog.size();j++){
          jCity.addItem(cityLog.get(j).getCityName());
    }
        
        jCity.setSelectedItem(c.getCityName());
        for(int k = 0; k< c.getCommunityCatalog().size();k++){
            jCommunity.addItem(c.getCommunityCatalog().get(k).getCommunityName());
        }
        jCommunity.setSelectedItem(comm.getCommunityName());
       // jCity.setEnabled(false);
        //jCommunity.setEnabled(false);
        for(int i = 0;i < comm.getHospitalCataloug().size();i++){
            jhospital.addItem((String)comm.getHospitalCataloug().get(i).getHospitalName());
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLChooseDate = new javax.swing.JLabel();
        jLSelectTime = new javax.swing.JLabel();
        jLSelectDoc = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jCity = new javax.swing.JComboBox<>();
        jCommunity = new javax.swing.JComboBox<>();
        jhospital = new javax.swing.JComboBox<>();
        jDoctor = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(170, 185, 207));

        jLChooseDate.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLChooseDate.setText("Choose Date:");

        jLSelectTime.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLSelectTime.setText("Select Time:");

        jLSelectDoc.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLSelectDoc.setText("Select Doctor:");

        jButton2.setBackground(new java.awt.Color(247, 247, 255));
        jButton2.setFont(new java.awt.Font("Lava Kannada", 0, 12)); // NOI18N
        jButton2.setText("Schedule");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jDateChooser1.setBackground(new java.awt.Color(247, 247, 255));

        jLabel1.setFont(new java.awt.Font("Lava Kannada", 1, 14)); // NOI18N
        jLabel1.setText("Schedule Appointment");

        jLabel2.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLabel2.setText("Select City:");

        jLabel3.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLabel3.setText("Select Community:");

        jLabel4.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jLabel4.setText("Select Hospital:");

        jCity.setBackground(new java.awt.Color(247, 247, 255));
        jCity.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCityActionPerformed(evt);
            }
        });

        jCommunity.setBackground(new java.awt.Color(247, 247, 255));
        jCommunity.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jCommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCommunityActionPerformed(evt);
            }
        });

        jhospital.setBackground(new java.awt.Color(247, 247, 255));
        jhospital.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N
        jhospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jhospitalActionPerformed(evt);
            }
        });

        jDoctor.setBackground(new java.awt.Color(247, 247, 255));
        jDoctor.setFont(new java.awt.Font("Lava Kannada", 0, 14)); // NOI18N

        jTextField1.setBackground(new java.awt.Color(247, 247, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 321, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(320, 320, 320))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(353, 353, 353)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLSelectDoc)
                            .addComponent(jLChooseDate)
                            .addComponent(jLSelectTime)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(jCity, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCommunity, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jhospital, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jDoctor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jhospital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLSelectDoc)
                            .addComponent(jDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLChooseDate))
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLSelectTime)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(71, 71, 71))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Date appointmentDate = jDateChooser1.getDate();
        String appointmentTime = jTextField1.getText();
        Appointments e = new Appointments();
        e.setAppointmentDate(appointmentDate);
        e.setAppointmentTime(appointmentTime);
        e.setPatient(p);
        String selDoctor = (String) jDoctor.getSelectedItem();
        for(int i = 0 ; i<comm.getHospitalCataloug().size();i++){
            Hospital hosp = comm.getHospitalCataloug().get(i);
            for(int j=0;j<hosp.getDoctorCataloug().size();j++){
                if(hosp.getDoctorCataloug().get(j).getPerson().getName().equalsIgnoreCase(selDoctor)){
                    hosp.getDoctorCataloug().get(j).getAppointmentCatalouge().addAppointment(e);
                     ReportPage rp = new ReportPage(jSplitPane2,p,comm, cityLog,new City());
                        jSplitPane2.setRightComponent(rp);
                    break;
                }
            }
        }
//        hosp.getPatientCatalouge().addPatient(people);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jhospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jhospitalActionPerformed
        // TODO add your handling code here:
       String selectedhos = (String)jhospital.getSelectedItem();
        HospitalCatalouge hosLog = comm.getHospitalCataloug();
        Hospital h = hosLog.searchHospital(selectedhos);
            
        if(h!= null){
        if(h.getDoctorCataloug()!= null){
            jDoctor.removeAllItems();;
          for(int i = 0 ; i < h.getDoctorCataloug().size();i++ ){
               jDoctor.addItem(h.getDoctorCataloug().get(i).getPerson().getName());
               }  
        } 
        }
           
        
    }//GEN-LAST:event_jhospitalActionPerformed

    private void jCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCityActionPerformed
        // TODO add your handling code here:
        String selectedCity = (String) jCity.getSelectedItem();
        City selected  = new City();
        jCommunity.removeAllItems();
        selected = cityLog.searchCity(selectedCity);
        for (int i =0;i<selected.getCommunityCatalog().size();i++){
            Community comm = new Community();
            comm = selected.getCommunityCatalog().get(i);
            jCommunity.addItem(comm.getCommunityName());

        }
    }//GEN-LAST:event_jCityActionPerformed

    private void jCommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCommunityActionPerformed
        // TODO add your handling code here:
        String selComm = (String)jCommunity.getSelectedItem();
                Community c1 = c.getCommunityCatalog().searchCommunity(selComm);
                jhospital.removeAllItems();
                if(c1!=null){
            for(int i = 0;i < c1.getHospitalCataloug().size();i++){      
            jhospital.addItem((String)c1.getHospitalCataloug().get(i).getHospitalName());
            }
        }
    }//GEN-LAST:event_jCommunityActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jCity;
    private javax.swing.JComboBox<String> jCommunity;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JComboBox<String> jDoctor;
    private javax.swing.JLabel jLChooseDate;
    private javax.swing.JLabel jLSelectDoc;
    private javax.swing.JLabel jLSelectTime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox<String> jhospital;
    // End of variables declaration//GEN-END:variables
}
