/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

/**
 *
 * @author namithajc
 */
public class ViewHospDetails extends javax.swing.JPanel {

    /**
     * Creates new form ViewHospDetails
     */
    public ViewHospDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLHospName = new javax.swing.JLabel();
        jLHospCity = new javax.swing.JLabel();
        jLHospCom = new javax.swing.JLabel();
        jLHospAdminName = new javax.swing.JLabel();
        jLHospAdminPhone = new javax.swing.JLabel();
        jLHospAdminEmail = new javax.swing.JLabel();
        jTHospName = new javax.swing.JTextField();
        jTHospCity = new javax.swing.JTextField();
        jTHospCom = new javax.swing.JTextField();
        jTHospAdminName = new javax.swing.JTextField();
        jTHospAdminPhone = new javax.swing.JTextField();
        jTAdminEmail = new javax.swing.JTextField();
        jTDocAv = new javax.swing.JTextField();
        jTDocPhone = new javax.swing.JTextField();
        jTDocEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLDocName = new javax.swing.JLabel();
        jLDocAge = new javax.swing.JLabel();
        jLDocSpec = new javax.swing.JLabel();
        jLDocAv = new javax.swing.JLabel();
        jLDocPhone = new javax.swing.JLabel();
        jLDocEmail = new javax.swing.JLabel();
        jTDocName = new javax.swing.JTextField();
        jTDocAge = new javax.swing.JTextField();
        jTDocSpec = new javax.swing.JTextField();
        jBtnHospEdit = new javax.swing.JButton();
        jBtnHospEdit1 = new javax.swing.JButton();

        jLabel1.setText("Hospital Details");

        jLHospName.setText("Name:");

        jLHospCity.setText("City:");

        jLHospCom.setText("Community:");

        jLHospAdminName.setText("Contact Person:");

        jLHospAdminPhone.setText("Phone:");

        jLHospAdminEmail.setText("Email");

        jTHospName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTHospNameActionPerformed(evt);
            }
        });

        jTHospCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTHospCityActionPerformed(evt);
            }
        });

        jTHospCom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTHospComActionPerformed(evt);
            }
        });

        jTHospAdminName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTHospAdminNameActionPerformed(evt);
            }
        });

        jTHospAdminPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTHospAdminPhoneActionPerformed(evt);
            }
        });

        jTAdminEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTAdminEmailActionPerformed(evt);
            }
        });

        jTDocAv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTDocAvActionPerformed(evt);
            }
        });

        jTDocPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTDocPhoneActionPerformed(evt);
            }
        });

        jTDocEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTDocEmailActionPerformed(evt);
            }
        });

        jLabel9.setText("Doctor Details");

        jLDocName.setText("Name:");

        jLDocAge.setText("Age:");

        jLDocSpec.setText("Specialization:");

        jLDocAv.setText("Availability:");

        jLDocPhone.setText("Phone:");

        jLDocEmail.setText("Email:");

        jTDocName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTDocNameActionPerformed(evt);
            }
        });

        jTDocAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTDocAgeActionPerformed(evt);
            }
        });

        jTDocSpec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTDocSpecActionPerformed(evt);
            }
        });

        jBtnHospEdit.setText("Edit Hospital");
        jBtnHospEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnHospEditActionPerformed(evt);
            }
        });

        jBtnHospEdit1.setText("Edit Doctor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLHospName, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLHospCity, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLHospCom, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLHospAdminName, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLHospAdminPhone, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLHospAdminEmail, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTHospName, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                            .addComponent(jTHospCity)
                                            .addComponent(jTHospCom)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jTHospAdminName))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTHospAdminPhone))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTAdminEmail))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(jBtnHospEdit))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel1)))
                .addGap(176, 176, 176)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(165, 165, 165))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBtnHospEdit1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLDocName, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLDocAge, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLDocSpec, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLDocAv, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLDocPhone, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLDocEmail, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jTDocAv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTDocPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTDocEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTDocAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTDocSpec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTDocName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(149, 149, 149))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLDocName)
                            .addComponent(jTDocName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLDocAge)
                            .addComponent(jTDocAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLDocSpec)
                            .addComponent(jTDocSpec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLDocAv)
                            .addComponent(jTDocAv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLDocPhone)
                            .addComponent(jTDocPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLDocEmail)
                            .addComponent(jTDocEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLHospName)
                            .addComponent(jTHospName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLHospCity)
                            .addComponent(jTHospCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLHospCom)
                            .addComponent(jTHospCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLHospAdminName)
                            .addComponent(jTHospAdminName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLHospAdminPhone)
                            .addComponent(jTHospAdminPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLHospAdminEmail)
                            .addComponent(jTAdminEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnHospEdit)
                    .addComponent(jBtnHospEdit1))
                .addContainerGap(120, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTHospNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTHospNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTHospNameActionPerformed

    private void jTHospCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTHospCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTHospCityActionPerformed

    private void jTHospComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTHospComActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTHospComActionPerformed

    private void jTHospAdminNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTHospAdminNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTHospAdminNameActionPerformed

    private void jTHospAdminPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTHospAdminPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTHospAdminPhoneActionPerformed

    private void jTAdminEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTAdminEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTAdminEmailActionPerformed

    private void jTDocAvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTDocAvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTDocAvActionPerformed

    private void jTDocPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTDocPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTDocPhoneActionPerformed

    private void jTDocEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTDocEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTDocEmailActionPerformed

    private void jTDocNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTDocNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTDocNameActionPerformed

    private void jTDocAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTDocAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTDocAgeActionPerformed

    private void jTDocSpecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTDocSpecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTDocSpecActionPerformed

    private void jBtnHospEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnHospEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnHospEditActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnHospEdit;
    private javax.swing.JButton jBtnHospEdit1;
    private javax.swing.JLabel jLDocAge;
    private javax.swing.JLabel jLDocAv;
    private javax.swing.JLabel jLDocEmail;
    private javax.swing.JLabel jLDocName;
    private javax.swing.JLabel jLDocPhone;
    private javax.swing.JLabel jLDocSpec;
    private javax.swing.JLabel jLHospAdminEmail;
    private javax.swing.JLabel jLHospAdminName;
    private javax.swing.JLabel jLHospAdminPhone;
    private javax.swing.JLabel jLHospCity;
    private javax.swing.JLabel jLHospCom;
    private javax.swing.JLabel jLHospName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTAdminEmail;
    private javax.swing.JTextField jTDocAge;
    private javax.swing.JTextField jTDocAv;
    private javax.swing.JTextField jTDocEmail;
    private javax.swing.JTextField jTDocName;
    private javax.swing.JTextField jTDocPhone;
    private javax.swing.JTextField jTDocSpec;
    private javax.swing.JTextField jTHospAdminName;
    private javax.swing.JTextField jTHospAdminPhone;
    private javax.swing.JTextField jTHospCity;
    private javax.swing.JTextField jTHospCom;
    private javax.swing.JTextField jTHospName;
    // End of variables declaration//GEN-END:variables
}
